"""
ViewGrid documentation screenshot inserter.

Usage:
    python tools/docs/insert_screenshots_into_docx.py \
        --docx docs/ViewGrid_Professional_Developer_User_Guide_v1.0.52.2_WithInlineScreenshots.docx \
        --screenshots docs/screenshots \
        --output docs/ViewGrid_Professional_Developer_User_Guide_v1.0.52.2_Completed.docx

The script reads docs/screenshots/viewgrid-docx-insert-map.json generated by
ViewGrid.TestApp > Documentation Capture Mode.

Default mode is inline:
- entries with TargetHeading are inserted below the matching DOCX heading;
- entries without a matching heading are appended to an "Unplaced" gallery.

Use --mode gallery for the legacy end-of-document gallery behavior.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

try:
    from docx import Document
    from docx.document import Document as DocumentObject
    from docx.oxml import OxmlElement
    from docx.text.paragraph import Paragraph
    from docx.shared import Inches
except ImportError as exc:
    raise SystemExit("python-docx is required. Install with: pip install python-docx") from exc


def normalize(value: str | None) -> str:
    return " ".join((value or "").strip().lower().split())


def insert_paragraph_after(paragraph: Paragraph, text: str = "", style: str | None = None) -> Paragraph:
    new_p = OxmlElement("w:p")
    paragraph._p.addnext(new_p)  # pylint: disable=protected-access
    new_para = Paragraph(new_p, paragraph._parent)  # pylint: disable=protected-access
    if style:
        try:
            new_para.style = style
        except Exception:
            pass
    if text:
        new_para.add_run(text)
    return new_para


def find_heading(doc: DocumentObject, target_heading: str | None) -> Paragraph | None:
    if not target_heading:
        return None

    target = normalize(target_heading)
    for paragraph in doc.paragraphs:
        text = normalize(paragraph.text)
        if not text:
            continue
        if text == target or text.startswith(target):
            return paragraph

    # Fallback: if the generated map contains "5. Kolon Sistemi", also accept "Kolon Sistemi".
    target_without_number = normalize(target_heading.split(".", 1)[1] if "." in target_heading else target_heading)
    for paragraph in doc.paragraphs:
        text = normalize(paragraph.text)
        if text == target_without_number or text.endswith(target_without_number):
            return paragraph

    return None


def add_entry_after(doc: DocumentObject, anchor: Paragraph, image_path: Path, entry: dict[str, Any]) -> Paragraph:
    description = entry.get("Description") or entry.get("ScenarioName") or ""
    caption = entry.get("Caption") or image_path.stem
    width = Inches(float(entry.get("SuggestedWidthInches", 6.4)))

    if description:
        anchor = insert_paragraph_after(anchor, str(description))

    picture_para = insert_paragraph_after(anchor)
    picture_para.alignment = 1
    picture_para.add_run().add_picture(str(image_path), width=width)

    caption_para = insert_paragraph_after(picture_para, str(caption))
    try:
        caption_para.style = "Caption"
    except Exception:
        pass

    return caption_para


def append_gallery(doc: DocumentObject, screenshot_dir: Path, entries: list[dict[str, Any]], title: str) -> int:
    doc.add_page_break()
    doc.add_heading(title, level=1)
    added = 0
    for entry in entries:
        image_path = screenshot_dir / entry["ImagePath"]
        if not image_path.exists():
            continue
        doc.add_heading(entry.get("Title", image_path.stem), level=2)
        doc.add_paragraph(entry.get("Description") or entry.get("ScenarioName") or "")
        doc.add_picture(str(image_path), width=Inches(float(entry.get("SuggestedWidthInches", 6.4))))
        doc.add_paragraph(entry.get("Caption", image_path.stem))
        added += 1
    return added


def main() -> int:
    parser = argparse.ArgumentParser(description="Insert ViewGrid screenshots into a DOCX file.")
    parser.add_argument("--docx", required=True, help="Source DOCX path")
    parser.add_argument("--screenshots", required=True, help="Folder generated by Documentation Capture Mode")
    parser.add_argument("--output", required=True, help="Output DOCX path")
    parser.add_argument("--mode", choices=["inline", "gallery", "both"], default="inline", help="Insertion mode. Default: inline")
    args = parser.parse_args()

    docx_path = Path(args.docx)
    screenshot_dir = Path(args.screenshots)
    output_path = Path(args.output)
    map_path = screenshot_dir / "viewgrid-docx-insert-map.json"

    if not docx_path.exists():
        raise SystemExit(f"DOCX not found: {docx_path}")
    if not map_path.exists():
        raise SystemExit(f"Insert map not found: {map_path}")

    entries: list[dict[str, Any]] = json.loads(map_path.read_text(encoding="utf-8"))
    doc = Document(str(docx_path))

    inserted = 0
    unplaced: list[dict[str, Any]] = []
    last_anchor_by_heading: dict[str, Paragraph] = {}

    if args.mode in {"inline", "both"}:
        for entry in entries:
            image_path = screenshot_dir / entry["ImagePath"]
            if not image_path.exists():
                continue

            target_heading = entry.get("TargetHeading")
            heading_key = normalize(target_heading)
            anchor = last_anchor_by_heading.get(heading_key) or find_heading(doc, target_heading)
            if anchor is None:
                unplaced.append(entry)
                continue

            last_anchor_by_heading[heading_key] = add_entry_after(doc, anchor, image_path, entry)
            inserted += 1

    if args.mode == "gallery":
        inserted += append_gallery(doc, screenshot_dir, entries, "Ek - ViewGrid Example Center Ekran Görüntüleri")
    elif args.mode == "both":
        inserted += append_gallery(doc, screenshot_dir, entries, "Ek - ViewGrid Example Center Ekran Görüntüleri")
    elif unplaced:
        inserted += append_gallery(doc, screenshot_dir, unplaced, "Ek - Yerleştirilemeyen ViewGrid Ekran Görüntüleri")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(output_path))
    print(f"Created: {output_path}")
    print(f"Inserted screenshots: {inserted}")
    if unplaced:
        print(f"Unplaced entries appended as gallery: {len(unplaced)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
