using System.Globalization;
using System.Text.Json;

namespace Taylan.Pano.Localization;

public static class PanoText
{
    private static readonly Dictionary<string, Dictionary<PanoLanguage, string>> Texts = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Filtering"] = new() { [PanoLanguage.Turkish]="Filtreleme", [PanoLanguage.English]="Filtering", [PanoLanguage.German]="Filtern", [PanoLanguage.French]="Filtrage", [PanoLanguage.Spanish]="Filtrado", [PanoLanguage.Italian]="Filtro", [PanoLanguage.Russian]="Фильтр", [PanoLanguage.Arabic]="تصفية", [PanoLanguage.Chinese]="筛选", [PanoLanguage.Japanese]="フィルター" },
        ["FilterStyle"] = new() { [PanoLanguage.Turkish]="Filtre stili", [PanoLanguage.English]="Filter style", [PanoLanguage.German]="Filterstil", [PanoLanguage.French]="Style de filtre", [PanoLanguage.Spanish]="Estilo de filtro", [PanoLanguage.Italian]="Stile filtro", [PanoLanguage.Russian]="Стиль фильтра", [PanoLanguage.Arabic]="نمط التصفية", [PanoLanguage.Chinese]="筛选样式", [PanoLanguage.Japanese]="フィルター形式" },
        ["SortAscending"] = new() { [PanoLanguage.Turkish]="Artan sırala", [PanoLanguage.English]="Sort ascending", [PanoLanguage.German]="Aufsteigend sortieren", [PanoLanguage.French]="Tri croissant", [PanoLanguage.Spanish]="Orden ascendente", [PanoLanguage.Italian]="Ordina crescente", [PanoLanguage.Russian]="По возрастанию", [PanoLanguage.Arabic]="ترتيب تصاعدي", [PanoLanguage.Chinese]="升序排序", [PanoLanguage.Japanese]="昇順で並べ替え" },
        ["SortDescending"] = new() { [PanoLanguage.Turkish]="Azalan sırala", [PanoLanguage.English]="Sort descending", [PanoLanguage.German]="Absteigend sortieren", [PanoLanguage.French]="Tri décroissant", [PanoLanguage.Spanish]="Orden descendente", [PanoLanguage.Italian]="Ordina decrescente", [PanoLanguage.Russian]="По убыванию", [PanoLanguage.Arabic]="ترتيب تنازلي", [PanoLanguage.Chinese]="降序排序", [PanoLanguage.Japanese]="降順で並べ替え" },
        ["Unsort"] = new() { [PanoLanguage.Turkish]="Sıralamayı kaldır", [PanoLanguage.English]="Unsort", [PanoLanguage.German]="Sortierung entfernen", [PanoLanguage.French]="Annuler le tri", [PanoLanguage.Spanish]="Quitar orden", [PanoLanguage.Italian]="Rimuovi ordinamento", [PanoLanguage.Russian]="Без сортировки", [PanoLanguage.Arabic]="إزالة الترتيب", [PanoLanguage.Chinese]="取消排序", [PanoLanguage.Japanese]="並べ替え解除" },
        ["ClearSort"] = new() { [PanoLanguage.Turkish]="Tüm sıralamayı temizle / default sıraya dön", [PanoLanguage.English]="Clear all sorting / return to default order", [PanoLanguage.German]="Alle Sortierungen löschen / Standardreihenfolge", [PanoLanguage.French]="Effacer tous les tris / ordre par défaut", [PanoLanguage.Spanish]="Borrar orden / volver al orden inicial", [PanoLanguage.Italian]="Cancella ordinamento / ordine predefinito", [PanoLanguage.Russian]="Очистить сортировку / порядок по умолчанию", [PanoLanguage.Arabic]="مسح الترتيب / العودة للوضع الافتراضي", [PanoLanguage.Chinese]="清除排序 / 恢复默认顺序", [PanoLanguage.Japanese]="すべての並べ替えを解除 / 既定順へ" },
        ["UnsortColumn"] = new() { [PanoLanguage.Turkish]="Bu kolonu unsort yap", [PanoLanguage.English]="Unsort this column", [PanoLanguage.German]="Diese Spalte unsortieren", [PanoLanguage.French]="Annuler le tri de cette colonne", [PanoLanguage.Spanish]="Quitar orden de esta columna", [PanoLanguage.Italian]="Rimuovi ordinamento colonna", [PanoLanguage.Russian]="Убрать сортировку столбца", [PanoLanguage.Arabic]="إزالة ترتيب هذا العمود", [PanoLanguage.Chinese]="取消此列排序", [PanoLanguage.Japanese]="この列の並べ替えを解除" },
        ["FreezeColumn"] = new() { [PanoLanguage.Turkish]="Bu kolonu sabitle", [PanoLanguage.English]="Freeze this column", [PanoLanguage.German]="Diese Spalte fixieren", [PanoLanguage.French]="Figer cette colonne", [PanoLanguage.Spanish]="Fijar esta columna", [PanoLanguage.Italian]="Blocca questa colonna", [PanoLanguage.Russian]="Закрепить столбец", [PanoLanguage.Arabic]="تثبيت هذا العمود", [PanoLanguage.Chinese]="冻结此列", [PanoLanguage.Japanese]="この列を固定" },
        ["ClearFrozenColumns"] = new() { [PanoLanguage.Turkish]="Sabit kolonları kaldır", [PanoLanguage.English]="Clear frozen columns", [PanoLanguage.German]="Fixierte Spalten lösen", [PanoLanguage.French]="Libérer les colonnes figées", [PanoLanguage.Spanish]="Quitar columnas fijadas", [PanoLanguage.Italian]="Sblocca colonne", [PanoLanguage.Russian]="Снять закрепление", [PanoLanguage.Arabic]="إلغاء تثبيت الأعمدة", [PanoLanguage.Chinese]="取消冻结列", [PanoLanguage.Japanese]="固定列を解除" },
        ["AutoSizeColumn"] = new() { [PanoLanguage.Turkish]="Kolon genişliğini otomatik ayarla", [PanoLanguage.English]="Auto size column", [PanoLanguage.German]="Spaltenbreite automatisch", [PanoLanguage.French]="Ajuster la colonne", [PanoLanguage.Spanish]="Autoajustar columna", [PanoLanguage.Italian]="Adatta colonna", [PanoLanguage.Russian]="Автоширина столбца", [PanoLanguage.Arabic]="ضبط عرض العمود تلقائياً", [PanoLanguage.Chinese]="自动调整列宽", [PanoLanguage.Japanese]="列幅を自動調整" },
        ["AutoSizeAllColumns"] = new() { [PanoLanguage.Turkish]="Tüm kolonları otomatik sığdır", [PanoLanguage.English]="Auto size all columns", [PanoLanguage.German]="Alle Spalten automatisch anpassen", [PanoLanguage.French]="Ajuster toutes les colonnes", [PanoLanguage.Spanish]="Autoajustar todas las columnas", [PanoLanguage.Italian]="Adatta tutte le colonne", [PanoLanguage.Russian]="Автоширина всех столбцов", [PanoLanguage.Arabic]="ضبط كل الأعمدة تلقائياً", [PanoLanguage.Chinese]="自动调整所有列", [PanoLanguage.Japanese]="すべての列幅を自動調整" },
        ["SaveColumnLayout"] = new() { [PanoLanguage.Turkish]="Kolon düzenini kaydet", [PanoLanguage.English]="Save column layout", [PanoLanguage.German]="Spaltenlayout speichern", [PanoLanguage.French]="Enregistrer la disposition", [PanoLanguage.Spanish]="Guardar diseño de columnas", [PanoLanguage.Italian]="Salva layout colonne", [PanoLanguage.Russian]="Сохранить порядок столбцов", [PanoLanguage.Arabic]="حفظ تخطيط الأعمدة", [PanoLanguage.Chinese]="保存列布局", [PanoLanguage.Japanese]="列レイアウトを保存" },
        ["LoadColumnLayout"] = new() { [PanoLanguage.Turkish]="Kolon düzenini yükle", [PanoLanguage.English]="Load column layout", [PanoLanguage.German]="Spaltenlayout laden", [PanoLanguage.French]="Charger la disposition", [PanoLanguage.Spanish]="Cargar diseño de columnas", [PanoLanguage.Italian]="Carica layout colonne", [PanoLanguage.Russian]="Загрузить порядок столбцов", [PanoLanguage.Arabic]="تحميل تخطيط الأعمدة", [PanoLanguage.Chinese]="加载列布局", [PanoLanguage.Japanese]="列レイアウトを読み込み" },
        ["ResetColumnLayout"] = new() { [PanoLanguage.Turkish]="Kolon düzenini sıfırla", [PanoLanguage.English]="Reset column layout", [PanoLanguage.German]="Spaltenlayout zurücksetzen", [PanoLanguage.French]="Réinitialiser la disposition", [PanoLanguage.Spanish]="Restablecer diseño de columnas", [PanoLanguage.Italian]="Reimposta layout colonne", [PanoLanguage.Russian]="Сбросить порядок столбцов", [PanoLanguage.Arabic]="إعادة ضبط تخطيط الأعمدة", [PanoLanguage.Chinese]="重置列布局", [PanoLanguage.Japanese]="列レイアウトをリセット" },
        ["ColumnChooserTitle"] = new() { [PanoLanguage.Turkish]="Kolon Seçici", [PanoLanguage.English]="Column chooser", [PanoLanguage.German]="Spaltenauswahl", [PanoLanguage.French]="Sélecteur de colonnes", [PanoLanguage.Spanish]="Selector de columnas", [PanoLanguage.Italian]="Selettore colonne", [PanoLanguage.Russian]="Выбор столбцов", [PanoLanguage.Arabic]="اختيار الأعمدة", [PanoLanguage.Chinese]="列选择器", [PanoLanguage.Japanese]="列の選択" },
        ["OK"] = new() { [PanoLanguage.Turkish]="Tamam", [PanoLanguage.English]="OK", [PanoLanguage.German]="OK", [PanoLanguage.French]="OK", [PanoLanguage.Spanish]="Aceptar", [PanoLanguage.Italian]="OK", [PanoLanguage.Russian]="OK", [PanoLanguage.Arabic]="موافق", [PanoLanguage.Chinese]="确定", [PanoLanguage.Japanese]="OK" },
        ["FastPreviewInfo"] = new() { [PanoLanguage.Turkish]="Hızlı önizleme; yazılan filtre tüm kayıtlara uygulanır.", [PanoLanguage.English]="Fast preview; typed filter applies to all rows.", [PanoLanguage.German]="Schnellvorschau; Textfilter gilt für alle Zeilen.", [PanoLanguage.French]="Aperçu rapide ; le texte filtre toutes les lignes.", [PanoLanguage.Spanish]="Vista rápida; el texto filtra todas las filas.", [PanoLanguage.Italian]="Anteprima rapida; il testo filtra tutte le righe.", [PanoLanguage.Russian]="Быстрый просмотр; текстовый фильтр применяется ко всем строкам.", [PanoLanguage.Arabic]="معاينة سريعة؛ النص يصفّي كل الصفوف.", [PanoLanguage.Chinese]="快速预览；输入筛选应用于所有行。", [PanoLanguage.Japanese]="高速プレビュー。入力フィルターは全行に適用。" },
        ["GroupByColumnPrefix"] = new() { [PanoLanguage.Turkish]="Bu kolona göre grupla:", [PanoLanguage.English]="Group by this column:", [PanoLanguage.German]="Nach dieser Spalte gruppieren:", [PanoLanguage.French]="Regrouper par cette colonne :", [PanoLanguage.Spanish]="Agrupar por esta columna:", [PanoLanguage.Italian]="Raggruppa per questa colonna:", [PanoLanguage.Russian]="Группировать по столбцу:", [PanoLanguage.Arabic]="تجميع حسب هذا العمود:", [PanoLanguage.Chinese]="按此列分组:", [PanoLanguage.Japanese]="この列でグループ化:" },
        ["CollapseAllGroups"] = new() { [PanoLanguage.Turkish]="Tüm grupları daralt", [PanoLanguage.English]="Collapse all groups", [PanoLanguage.German]="Alle Gruppen einklappen", [PanoLanguage.French]="Réduire tous les groupes", [PanoLanguage.Spanish]="Contraer todos los grupos", [PanoLanguage.Italian]="Comprimi tutti i gruppi", [PanoLanguage.Russian]="Свернуть группы", [PanoLanguage.Arabic]="طي كل المجموعات", [PanoLanguage.Chinese]="折叠所有分组", [PanoLanguage.Japanese]="すべてのグループを折りたたむ" },
        ["ExpandAllGroups"] = new() { [PanoLanguage.Turkish]="Tüm grupları aç", [PanoLanguage.English]="Expand all groups", [PanoLanguage.German]="Alle Gruppen ausklappen", [PanoLanguage.French]="Développer tous les groupes", [PanoLanguage.Spanish]="Expandir todos los grupos", [PanoLanguage.Italian]="Espandi tutti i gruppi", [PanoLanguage.Russian]="Развернуть группы", [PanoLanguage.Arabic]="فتح كل المجموعات", [PanoLanguage.Chinese]="展开所有分组", [PanoLanguage.Japanese]="すべてのグループを展開" },
        ["ClearGrouping"] = new() { [PanoLanguage.Turkish]="Gruplamayı kaldır", [PanoLanguage.English]="Clear grouping", [PanoLanguage.German]="Gruppierung entfernen", [PanoLanguage.French]="Effacer le regroupement", [PanoLanguage.Spanish]="Quitar agrupación", [PanoLanguage.Italian]="Rimuovi raggruppamento", [PanoLanguage.Russian]="Убрать группировку", [PanoLanguage.Arabic]="إزالة التجميع", [PanoLanguage.Chinese]="清除分组", [PanoLanguage.Japanese]="グループ化を解除" },
        ["CollapseThisGroup"] = new() { [PanoLanguage.Turkish]="Bu grubu daralt", [PanoLanguage.English]="Collapse this group", [PanoLanguage.German]="Diese Gruppe einklappen", [PanoLanguage.French]="Réduire ce groupe", [PanoLanguage.Spanish]="Contraer este grupo", [PanoLanguage.Italian]="Comprimi questo gruppo", [PanoLanguage.Russian]="Свернуть эту группу", [PanoLanguage.Arabic]="طي هذه المجموعة", [PanoLanguage.Chinese]="折叠此分组", [PanoLanguage.Japanese]="このグループを折りたたむ" },
        ["ExpandThisGroup"] = new() { [PanoLanguage.Turkish]="Bu grubu aç", [PanoLanguage.English]="Expand this group", [PanoLanguage.German]="Diese Gruppe ausklappen", [PanoLanguage.French]="Développer ce groupe", [PanoLanguage.Spanish]="Expandir este grupo", [PanoLanguage.Italian]="Espandi questo gruppo", [PanoLanguage.Russian]="Развернуть эту группу", [PanoLanguage.Arabic]="فتح هذه المجموعة", [PanoLanguage.Chinese]="展开此分组", [PanoLanguage.Japanese]="このグループを展開" },
        ["ShowOnlyThisGroup"] = new() { [PanoLanguage.Turkish]="Sadece bu grubu açık bırak", [PanoLanguage.English]="Keep only this group open", [PanoLanguage.German]="Nur diese Gruppe offen lassen", [PanoLanguage.French]="Garder seulement ce groupe ouvert", [PanoLanguage.Spanish]="Dejar abierto solo este grupo", [PanoLanguage.Italian]="Lascia aperto solo questo gruppo", [PanoLanguage.Russian]="Оставить открытой только эту группу", [PanoLanguage.Arabic]="إبقاء هذه المجموعة فقط مفتوحة", [PanoLanguage.Chinese]="仅保持此分组展开", [PanoLanguage.Japanese]="このグループだけ開いたままにする" },
        ["ViewMode"] = new() { [PanoLanguage.Turkish]="Görünüm modu", [PanoLanguage.English]="View mode", [PanoLanguage.German]="Ansichtsmodus", [PanoLanguage.French]="Mode d'affichage", [PanoLanguage.Spanish]="Modo de vista", [PanoLanguage.Italian]="Modalità vista", [PanoLanguage.Russian]="Режим просмотра", [PanoLanguage.Arabic]="نمط العرض", [PanoLanguage.Chinese]="视图模式", [PanoLanguage.Japanese]="表示モード" },
        ["ChooseColumns"] = new() { [PanoLanguage.Turkish]="Kolonları seç...", [PanoLanguage.English]="Choose columns...", [PanoLanguage.German]="Spalten wählen...", [PanoLanguage.French]="Choisir les colonnes...", [PanoLanguage.Spanish]="Elegir columnas...", [PanoLanguage.Italian]="Scegli colonne...", [PanoLanguage.Russian]="Выбрать столбцы...", [PanoLanguage.Arabic]="اختيار الأعمدة...", [PanoLanguage.Chinese]="选择列...", [PanoLanguage.Japanese]="列を選択..." },
        ["ClearFilters"] = new() { [PanoLanguage.Turkish]="Filtreleri Temizle", [PanoLanguage.English]="Clear Filters", [PanoLanguage.German]="Filter löschen", [PanoLanguage.French]="Effacer les filtres", [PanoLanguage.Spanish]="Borrar filtros", [PanoLanguage.Italian]="Cancella filtri", [PanoLanguage.Russian]="Очистить фильтры", [PanoLanguage.Arabic]="مسح عوامل التصفية", [PanoLanguage.Chinese]="清除筛选", [PanoLanguage.Japanese]="フィルターをクリア" },
        ["ClearAllFilters"] = new() { [PanoLanguage.Turkish]="Tüm filtreleri temizle", [PanoLanguage.English]="Clear all filters", [PanoLanguage.German]="Alle Filter löschen", [PanoLanguage.French]="Effacer tous les filtres", [PanoLanguage.Spanish]="Borrar todos los filtros", [PanoLanguage.Italian]="Cancella tutti i filtri", [PanoLanguage.Russian]="Очистить все фильтры", [PanoLanguage.Arabic]="مسح كل عوامل التصفية", [PanoLanguage.Chinese]="清除所有筛选", [PanoLanguage.Japanese]="すべてのフィルターをクリア" },
        ["SearchPlaceholder"] = new() { [PanoLanguage.Turkish]="Aranacak / filtrelenecek değer...", [PanoLanguage.English]="Search / filter value...", [PanoLanguage.German]="Such-/Filterwert...", [PanoLanguage.French]="Valeur à rechercher / filtrer...", [PanoLanguage.Spanish]="Valor a buscar / filtrar...", [PanoLanguage.Italian]="Valore da cercare / filtrare...", [PanoLanguage.Russian]="Поиск / значение фильтра...", [PanoLanguage.Arabic]="قيمة البحث / التصفية...", [PanoLanguage.Chinese]="搜索 / 筛选值...", [PanoLanguage.Japanese]="検索 / フィルター値..." },
        ["ApplyTypedTextAsFilter"] = new() { [PanoLanguage.Turkish]="Yazılan metni filtre olarak uygula", [PanoLanguage.English]="Apply typed text as filter", [PanoLanguage.German]="Eingabetext als Filter verwenden", [PanoLanguage.French]="Appliquer le texte saisi comme filtre", [PanoLanguage.Spanish]="Aplicar texto escrito como filtro", [PanoLanguage.Italian]="Usa il testo come filtro", [PanoLanguage.Russian]="Применить введенный текст", [PanoLanguage.Arabic]="تطبيق النص المكتوب كتصفية", [PanoLanguage.Chinese]="将输入文本作为筛选", [PanoLanguage.Japanese]="入力テキストをフィルターに適用" },
        ["SearchTypedTextInColumn"] = new() { [PanoLanguage.Turkish]="Yazılan metni kolonda ara", [PanoLanguage.English]="Search typed text in column", [PanoLanguage.German]="Text in Spalte suchen", [PanoLanguage.French]="Chercher le texte dans la colonne", [PanoLanguage.Spanish]="Buscar texto en la columna", [PanoLanguage.Italian]="Cerca testo nella colonna", [PanoLanguage.Russian]="Искать текст в столбце", [PanoLanguage.Arabic]="البحث عن النص في العمود", [PanoLanguage.Chinese]="在列中搜索输入文本", [PanoLanguage.Japanese]="列内で入力テキストを検索" },
        ["SelectAll"] = new() { [PanoLanguage.Turkish]="Tümünü seç", [PanoLanguage.English]="Select All", [PanoLanguage.German]="Alle auswählen", [PanoLanguage.French]="Tout sélectionner", [PanoLanguage.Spanish]="Seleccionar todo", [PanoLanguage.Italian]="Seleziona tutto", [PanoLanguage.Russian]="Выбрать все", [PanoLanguage.Arabic]="تحديد الكل", [PanoLanguage.Chinese]="全选", [PanoLanguage.Japanese]="すべて選択" },
        ["Apply"] = new() { [PanoLanguage.Turkish]="Uygula", [PanoLanguage.English]="Apply", [PanoLanguage.German]="Anwenden", [PanoLanguage.French]="Appliquer", [PanoLanguage.Spanish]="Aplicar", [PanoLanguage.Italian]="Applica", [PanoLanguage.Russian]="Применить", [PanoLanguage.Arabic]="تطبيق", [PanoLanguage.Chinese]="应用", [PanoLanguage.Japanese]="適用" },
        ["Clear"] = new() { [PanoLanguage.Turkish]="Temizle", [PanoLanguage.English]="Clear", [PanoLanguage.German]="Löschen", [PanoLanguage.French]="Effacer", [PanoLanguage.Spanish]="Limpiar", [PanoLanguage.Italian]="Cancella", [PanoLanguage.Russian]="Очистить", [PanoLanguage.Arabic]="مسح", [PanoLanguage.Chinese]="清除", [PanoLanguage.Japanese]="クリア" },
        ["SeparateFilterWindow"] = new() { [PanoLanguage.Turkish]="Ayrı filtre penceresi...", [PanoLanguage.English]="Separate filter window...", [PanoLanguage.German]="Separates Filterfenster...", [PanoLanguage.French]="Fenêtre de filtre séparée...", [PanoLanguage.Spanish]="Ventana de filtro separada...", [PanoLanguage.Italian]="Finestra filtro separata...", [PanoLanguage.Russian]="Отдельное окно фильтра...", [PanoLanguage.Arabic]="نافذة تصفية منفصلة...", [PanoLanguage.Chinese]="单独筛选窗口...", [PanoLanguage.Japanese]="別のフィルターウィンドウ..." },
        ["EmptyList"] = new() { [PanoLanguage.Turkish]="Liste boş", [PanoLanguage.English]="List is empty", [PanoLanguage.German]="Liste ist leer", [PanoLanguage.French]="La liste est vide", [PanoLanguage.Spanish]="La lista está vacía", [PanoLanguage.Italian]="La lista è vuota", [PanoLanguage.Russian]="Список пуст", [PanoLanguage.Arabic]="القائمة فارغة", [PanoLanguage.Chinese]="列表为空", [PanoLanguage.Japanese]="リストは空です" },

        ["ColumnFilterSuffix"] = new() { [PanoLanguage.Turkish]="filtresi", [PanoLanguage.English]="filter", [PanoLanguage.German]="Filter", [PanoLanguage.French]="filtre", [PanoLanguage.Spanish]="filtro", [PanoLanguage.Italian]="filtro", [PanoLanguage.Russian]="фильтр", [PanoLanguage.Arabic]="تصفية", [PanoLanguage.Chinese]="筛选", [PanoLanguage.Japanese]="フィルター" },
        ["FilterWindowSuffix"] = new() { [PanoLanguage.Turkish]="filtre penceresi...", [PanoLanguage.English]="filter window...", [PanoLanguage.German]="Filterfenster...", [PanoLanguage.French]="fenêtre de filtre...", [PanoLanguage.Spanish]="ventana de filtro...", [PanoLanguage.Italian]="finestra filtro...", [PanoLanguage.Russian]="окно фильтра...", [PanoLanguage.Arabic]="نافذة التصفية...", [PanoLanguage.Chinese]="筛选窗口...", [PanoLanguage.Japanese]="フィルターウィンドウ..." },
        ["EmptyValue"] = new() { [PanoLanguage.Turkish]="(Boş)", [PanoLanguage.English]="(Empty)", [PanoLanguage.German]="(Leer)", [PanoLanguage.French]="(Vide)", [PanoLanguage.Spanish]="(Vacío)", [PanoLanguage.Italian]="(Vuoto)", [PanoLanguage.Russian]="(Пусто)", [PanoLanguage.Arabic]="(فارغ)", [PanoLanguage.Chinese]="(空)", [PanoLanguage.Japanese]="(空)" },
        ["Copy"] = new() { [PanoLanguage.Turkish]="Kopyala", [PanoLanguage.English]="Copy", [PanoLanguage.German]="Kopieren", [PanoLanguage.French]="Copier", [PanoLanguage.Spanish]="Copiar", [PanoLanguage.Italian]="Copia", [PanoLanguage.Russian]="Копировать", [PanoLanguage.Arabic]="نسخ", [PanoLanguage.Chinese]="复制", [PanoLanguage.Japanese]="コピー" },
        ["Paste"] = new() { [PanoLanguage.Turkish]="Yapıştır", [PanoLanguage.English]="Paste", [PanoLanguage.German]="Einfügen", [PanoLanguage.French]="Coller", [PanoLanguage.Spanish]="Pegar", [PanoLanguage.Italian]="Incolla", [PanoLanguage.Russian]="Вставить", [PanoLanguage.Arabic]="لصق", [PanoLanguage.Chinese]="粘贴", [PanoLanguage.Japanese]="貼り付け" },
        ["EditCell"] = new() { [PanoLanguage.Turkish]="Hücreyi Düzenle", [PanoLanguage.English]="Edit cell", [PanoLanguage.German]="Zelle bearbeiten", [PanoLanguage.French]="Modifier la cellule", [PanoLanguage.Spanish]="Editar celda", [PanoLanguage.Italian]="Modifica cella", [PanoLanguage.Russian]="Редактировать ячейку", [PanoLanguage.Arabic]="تحرير الخلية", [PanoLanguage.Chinese]="编辑单元格", [PanoLanguage.Japanese]="セルを編集" },
        ["RowDetails"] = new() { [PanoLanguage.Turkish]="Satır Detayı", [PanoLanguage.English]="Row details", [PanoLanguage.German]="Zeilendetails", [PanoLanguage.French]="Détails de ligne", [PanoLanguage.Spanish]="Detalles de fila", [PanoLanguage.Italian]="Dettagli riga", [PanoLanguage.Russian]="Детали строки", [PanoLanguage.Arabic]="تفاصيل الصف", [PanoLanguage.Chinese]="行详情", [PanoLanguage.Japanese]="行の詳細" },
        ["PopupMenu"] = new() { [PanoLanguage.Turkish]="Popup menü", [PanoLanguage.English]="Popup menu", [PanoLanguage.German]="Popup-Menü", [PanoLanguage.French]="Menu popup", [PanoLanguage.Spanish]="Menú emergente", [PanoLanguage.Italian]="Menu popup", [PanoLanguage.Russian]="Всплывающее меню", [PanoLanguage.Arabic]="قائمة منبثقة", [PanoLanguage.Chinese]="弹出菜单", [PanoLanguage.Japanese]="ポップアップメニュー" },
        ["ModalWindow"] = new() { [PanoLanguage.Turkish]="Ayrı pencere", [PanoLanguage.English]="Separate window", [PanoLanguage.German]="Separates Fenster", [PanoLanguage.French]="Fenêtre séparée", [PanoLanguage.Spanish]="Ventana separada", [PanoLanguage.Italian]="Finestra separata", [PanoLanguage.Russian]="Отдельное окно", [PanoLanguage.Arabic]="نافذة منفصلة", [PanoLanguage.Chinese]="独立窗口", [PanoLanguage.Japanese]="別ウィンドウ" },
        ["Both"] = new() { [PanoLanguage.Turkish]="İkisi birlikte", [PanoLanguage.English]="Both", [PanoLanguage.German]="Beide", [PanoLanguage.French]="Les deux", [PanoLanguage.Spanish]="Ambos", [PanoLanguage.Italian]="Entrambi", [PanoLanguage.Russian]="Оба", [PanoLanguage.Arabic]="كلاهما", [PanoLanguage.Chinese]="两者", [PanoLanguage.Japanese]="両方" },
        ["ExtraLarge"] = new() { [PanoLanguage.Turkish]="Kompakt", [PanoLanguage.English]="Extra large", [PanoLanguage.German]="Sehr groß", [PanoLanguage.French]="Très grand", [PanoLanguage.Spanish]="Muy grande", [PanoLanguage.Italian]="Molto grande", [PanoLanguage.Russian]="Очень крупный", [PanoLanguage.Arabic]="كبير جداً", [PanoLanguage.Chinese]="超大", [PanoLanguage.Japanese]="特大" },
        ["Large"] = new() { [PanoLanguage.Turkish]="Standart", [PanoLanguage.English]="Large", [PanoLanguage.German]="Groß", [PanoLanguage.French]="Grand", [PanoLanguage.Spanish]="Grande", [PanoLanguage.Italian]="Grande", [PanoLanguage.Russian]="Крупный", [PanoLanguage.Arabic]="كبير", [PanoLanguage.Chinese]="大", [PanoLanguage.Japanese]="大" },
        ["Medium"] = new() { [PanoLanguage.Turkish]="Geniş", [PanoLanguage.English]="Medium", [PanoLanguage.German]="Mittel", [PanoLanguage.French]="Moyen", [PanoLanguage.Spanish]="Medio", [PanoLanguage.Italian]="Medio", [PanoLanguage.Russian]="Средний", [PanoLanguage.Arabic]="متوسط", [PanoLanguage.Chinese]="中", [PanoLanguage.Japanese]="中" },
        ["List"] = new() { [PanoLanguage.Turkish]="Liste", [PanoLanguage.English]="List", [PanoLanguage.German]="Liste", [PanoLanguage.French]="Liste", [PanoLanguage.Spanish]="Lista", [PanoLanguage.Italian]="Lista", [PanoLanguage.Russian]="Список", [PanoLanguage.Arabic]="قائمة", [PanoLanguage.Chinese]="列表", [PanoLanguage.Japanese]="リスト" },
        ["Details"] = new() { [PanoLanguage.Turkish]="Detay", [PanoLanguage.English]="Details", [PanoLanguage.German]="Details", [PanoLanguage.French]="Détails", [PanoLanguage.Spanish]="Detalles", [PanoLanguage.Italian]="Dettagli", [PanoLanguage.Russian]="Подробности", [PanoLanguage.Arabic]="تفاصيل", [PanoLanguage.Chinese]="详细信息", [PanoLanguage.Japanese]="詳細" },
        ["Tiles"] = new() { [PanoLanguage.Turkish]="Kart", [PanoLanguage.English]="Tile / Card", [PanoLanguage.German]="Kachel / Karte", [PanoLanguage.French]="Tuile / Carte", [PanoLanguage.Spanish]="Mosaico / Tarjeta", [PanoLanguage.Italian]="Riquadro / Scheda", [PanoLanguage.Russian]="Плитка / Карточка", [PanoLanguage.Arabic]="بطاقة / مربع", [PanoLanguage.Chinese]="磁贴 / 卡片", [PanoLanguage.Japanese]="タイル / カード" },

        ["Columns"] = new() { [PanoLanguage.Turkish]="Kolonlar", [PanoLanguage.English]="Columns", [PanoLanguage.German]="Spalten", [PanoLanguage.French]="Colonnes", [PanoLanguage.Spanish]="Columnas", [PanoLanguage.Italian]="Colonne", [PanoLanguage.Russian]="Столбцы", [PanoLanguage.Arabic]="الأعمدة", [PanoLanguage.Chinese]="列", [PanoLanguage.Japanese]="列" },
        ["ShowAll"] = new() { [PanoLanguage.Turkish]="Tümünü göster", [PanoLanguage.English]="Show all", [PanoLanguage.German]="Alle anzeigen", [PanoLanguage.French]="Tout afficher", [PanoLanguage.Spanish]="Mostrar todo", [PanoLanguage.Italian]="Mostra tutto", [PanoLanguage.Russian]="Показать все", [PanoLanguage.Arabic]="إظهار الكل", [PanoLanguage.Chinese]="全部显示", [PanoLanguage.Japanese]="すべて表示" },
        ["HideAll"] = new() { [PanoLanguage.Turkish]="Tümünü gizle", [PanoLanguage.English]="Hide all", [PanoLanguage.German]="Alle ausblenden", [PanoLanguage.French]="Tout masquer", [PanoLanguage.Spanish]="Ocultar todo", [PanoLanguage.Italian]="Nascondi tutto", [PanoLanguage.Russian]="Скрыть все", [PanoLanguage.Arabic]="إخفاء الكل", [PanoLanguage.Chinese]="全部隐藏", [PanoLanguage.Japanese]="すべて非表示" },
        ["DefaultColumnLayout"] = new() { [PanoLanguage.Turkish]="Varsayılan kolon düzeni", [PanoLanguage.English]="Default column layout", [PanoLanguage.German]="Standard-Spaltenlayout", [PanoLanguage.French]="Disposition de colonnes par défaut", [PanoLanguage.Spanish]="Diseño de columnas predeterminado", [PanoLanguage.Italian]="Layout colonne predefinito", [PanoLanguage.Russian]="Стандартный порядок столбцов", [PanoLanguage.Arabic]="تخطيط الأعمدة الافتراضي", [PanoLanguage.Chinese]="默认列布局", [PanoLanguage.Japanese]="既定の列レイアウト" },
        ["FitVisibleColumns"] = new() { [PanoLanguage.Turkish]="Görünür kolonları sığdır", [PanoLanguage.English]="Fit visible columns", [PanoLanguage.German]="Sichtbare Spalten anpassen", [PanoLanguage.French]="Ajuster les colonnes visibles", [PanoLanguage.Spanish]="Ajustar columnas visibles", [PanoLanguage.Italian]="Adatta colonne visibili", [PanoLanguage.Russian]="Подогнать видимые столбцы", [PanoLanguage.Arabic]="ملاءمة الأعمدة المرئية", [PanoLanguage.Chinese]="适应可见列", [PanoLanguage.Japanese]="表示列を合わせる" },
        ["ColumnChooserWindow"] = new() { [PanoLanguage.Turkish]="Kolon seçici penceresi...", [PanoLanguage.English]="Column chooser window...", [PanoLanguage.German]="Spaltenauswahlfenster...", [PanoLanguage.French]="Fenêtre de sélection des colonnes...", [PanoLanguage.Spanish]="Ventana de selección de columnas...", [PanoLanguage.Italian]="Finestra selettore colonne...", [PanoLanguage.Russian]="Окно выбора столбцов...", [PanoLanguage.Arabic]="نافذة اختيار الأعمدة...", [PanoLanguage.Chinese]="列选择窗口...", [PanoLanguage.Japanese]="列選択ウィンドウ..." },
        ["ColumnSearchPlaceholder"] = new() { [PanoLanguage.Turkish]="Kolon ara...", [PanoLanguage.English]="Search columns...", [PanoLanguage.German]="Spalten suchen...", [PanoLanguage.French]="Rechercher des colonnes...", [PanoLanguage.Spanish]="Buscar columnas...", [PanoLanguage.Italian]="Cerca colonne...", [PanoLanguage.Russian]="Поиск столбцов...", [PanoLanguage.Arabic]="بحث في الأعمدة...", [PanoLanguage.Chinese]="搜索列...", [PanoLanguage.Japanese]="列を検索..." },
        ["Cancel"] = new() { [PanoLanguage.Turkish]="İptal", [PanoLanguage.English]="Cancel", [PanoLanguage.German]="Abbrechen", [PanoLanguage.French]="Annuler", [PanoLanguage.Spanish]="Cancelar", [PanoLanguage.Italian]="Annulla", [PanoLanguage.Russian]="Отмена", [PanoLanguage.Arabic]="إلغاء", [PanoLanguage.Chinese]="取消", [PanoLanguage.Japanese]="キャンセル" },
        ["ClearColumnFilter"] = new() { [PanoLanguage.Turkish]="Bu kolonun filtresini temizle", [PanoLanguage.English]="Clear this column filter", [PanoLanguage.German]="Filter dieser Spalte löschen", [PanoLanguage.French]="Effacer le filtre de cette colonne", [PanoLanguage.Spanish]="Borrar filtro de esta columna", [PanoLanguage.Italian]="Cancella filtro colonna", [PanoLanguage.Russian]="Очистить фильтр столбца", [PanoLanguage.Arabic]="مسح فلتر هذا العمود", [PanoLanguage.Chinese]="清除此列筛选", [PanoLanguage.Japanese]="この列のフィルターをクリア" },
        ["CopyCell"] = new() { [PanoLanguage.Turkish]="Hücreyi kopyala", [PanoLanguage.English]="Copy cell", [PanoLanguage.German]="Zelle kopieren", [PanoLanguage.French]="Copier la cellule", [PanoLanguage.Spanish]="Copiar celda", [PanoLanguage.Italian]="Copia cella", [PanoLanguage.Russian]="Копировать ячейку", [PanoLanguage.Arabic]="نسخ الخلية", [PanoLanguage.Chinese]="复制单元格", [PanoLanguage.Japanese]="セルをコピー" },
        ["CopySelectionJson"] = new() { [PanoLanguage.Turkish]="Seçimi JSON kopyala", [PanoLanguage.English]="Copy selection as JSON", [PanoLanguage.German]="Auswahl als JSON kopieren", [PanoLanguage.French]="Copier la sélection en JSON", [PanoLanguage.Spanish]="Copiar selección como JSON", [PanoLanguage.Italian]="Copia selezione come JSON", [PanoLanguage.Russian]="Копировать выбор как JSON", [PanoLanguage.Arabic]="نسخ التحديد كـ JSON", [PanoLanguage.Chinese]="复制选择为 JSON", [PanoLanguage.Japanese]="選択をJSONでコピー" },
        ["CopyMiniAnalytics"] = new() { [PanoLanguage.Turkish]="Mini analytics kopyala", [PanoLanguage.English]="Copy mini analytics", [PanoLanguage.German]="Mini-Analyse kopieren", [PanoLanguage.French]="Copier la mini-analyse", [PanoLanguage.Spanish]="Copiar mini análisis", [PanoLanguage.Italian]="Copia mini analisi", [PanoLanguage.Russian]="Копировать мини-аналитику", [PanoLanguage.Arabic]="نسخ التحليل المصغر", [PanoLanguage.Chinese]="复制迷你分析", [PanoLanguage.Japanese]="ミニ分析をコピー" },
        ["Mode"] = new() { [PanoLanguage.Turkish]="Çalışma modu", [PanoLanguage.English]="Mode", [PanoLanguage.German]="Modus", [PanoLanguage.French]="Mode", [PanoLanguage.Spanish]="Modo", [PanoLanguage.Italian]="Modalità", [PanoLanguage.Russian]="Режим", [PanoLanguage.Arabic]="الوضع", [PanoLanguage.Chinese]="模式", [PanoLanguage.Japanese]="モード" },
        ["Theme"] = new() { [PanoLanguage.Turkish]="Tema", [PanoLanguage.English]="Theme", [PanoLanguage.German]="Design", [PanoLanguage.French]="Thème", [PanoLanguage.Spanish]="Tema", [PanoLanguage.Italian]="Tema", [PanoLanguage.Russian]="Тема", [PanoLanguage.Arabic]="السمة", [PanoLanguage.Chinese]="主题", [PanoLanguage.Japanese]="テーマ" },
        ["Sorting"] = new() { [PanoLanguage.Turkish]="Sıralama", [PanoLanguage.English]="Sorting", [PanoLanguage.German]="Sortierung", [PanoLanguage.French]="Tri", [PanoLanguage.Spanish]="Ordenación", [PanoLanguage.Italian]="Ordinamento", [PanoLanguage.Russian]="Сортировка", [PanoLanguage.Arabic]="الترتيب", [PanoLanguage.Chinese]="排序", [PanoLanguage.Japanese]="並べ替え" },
        ["FrozenColumn"] = new() { [PanoLanguage.Turkish]="Sabit kolon", [PanoLanguage.English]="Frozen column", [PanoLanguage.German]="Fixierte Spalte", [PanoLanguage.French]="Colonne figée", [PanoLanguage.Spanish]="Columna fijada", [PanoLanguage.Italian]="Colonna bloccata", [PanoLanguage.Russian]="Закрепленный столбец", [PanoLanguage.Arabic]="عمود مثبت", [PanoLanguage.Chinese]="冻结列", [PanoLanguage.Japanese]="固定列" },
        ["ColumnWidth"] = new() { [PanoLanguage.Turkish]="Kolon genişliği", [PanoLanguage.English]="Column width", [PanoLanguage.German]="Spaltenbreite", [PanoLanguage.French]="Largeur de colonne", [PanoLanguage.Spanish]="Ancho de columna", [PanoLanguage.Italian]="Larghezza colonna", [PanoLanguage.Russian]="Ширина столбца", [PanoLanguage.Arabic]="عرض العمود", [PanoLanguage.Chinese]="列宽", [PanoLanguage.Japanese]="列幅" },
        ["Layout"] = new() { [PanoLanguage.Turkish]="Düzen", [PanoLanguage.English]="Layout", [PanoLanguage.German]="Layout", [PanoLanguage.French]="Disposition", [PanoLanguage.Spanish]="Diseño", [PanoLanguage.Italian]="Layout", [PanoLanguage.Russian]="Макет", [PanoLanguage.Arabic]="التخطيط", [PanoLanguage.Chinese]="布局", [PanoLanguage.Japanese]="レイアウト" },
        ["SaveDefaultLayoutProfile"] = new() { [PanoLanguage.Turkish]="Layout profilini kaydet: Default", [PanoLanguage.English]="Save layout profile: Default", [PanoLanguage.German]="Layoutprofil speichern: Default", [PanoLanguage.French]="Enregistrer le profil : Default", [PanoLanguage.Spanish]="Guardar perfil: Default", [PanoLanguage.Italian]="Salva profilo: Default", [PanoLanguage.Russian]="Сохранить профиль: Default", [PanoLanguage.Arabic]="حفظ ملف التخطيط: Default", [PanoLanguage.Chinese]="保存布局配置: Default", [PanoLanguage.Japanese]="レイアウトプロファイル保存: Default" },
        ["LayoutProfiles"] = new() { [PanoLanguage.Turkish]="Layout profilleri", [PanoLanguage.English]="Layout profiles", [PanoLanguage.German]="Layoutprofile", [PanoLanguage.French]="Profils de disposition", [PanoLanguage.Spanish]="Perfiles de diseño", [PanoLanguage.Italian]="Profili layout", [PanoLanguage.Russian]="Профили макета", [PanoLanguage.Arabic]="ملفات التخطيط", [PanoLanguage.Chinese]="布局配置", [PanoLanguage.Japanese]="レイアウトプロファイル" },
        ["SaveUserLayout"] = new() { [PanoLanguage.Turkish]="Kullanıcı düzenini kaydet", [PanoLanguage.English]="Save user layout", [PanoLanguage.German]="Benutzerlayout speichern", [PanoLanguage.French]="Enregistrer la disposition utilisateur", [PanoLanguage.Spanish]="Guardar diseño de usuario", [PanoLanguage.Italian]="Salva layout utente", [PanoLanguage.Russian]="Сохранить макет пользователя", [PanoLanguage.Arabic]="حفظ تخطيط المستخدم", [PanoLanguage.Chinese]="保存用户布局", [PanoLanguage.Japanese]="ユーザーレイアウトを保存" },
        ["LoadUserLayout"] = new() { [PanoLanguage.Turkish]="Kullanıcı düzenini yükle", [PanoLanguage.English]="Load user layout", [PanoLanguage.German]="Benutzerlayout laden", [PanoLanguage.French]="Charger la disposition utilisateur", [PanoLanguage.Spanish]="Cargar diseño de usuario", [PanoLanguage.Italian]="Carica layout utente", [PanoLanguage.Russian]="Загрузить макет пользователя", [PanoLanguage.Arabic]="تحميل تخطيط المستخدم", [PanoLanguage.Chinese]="加载用户布局", [PanoLanguage.Japanese]="ユーザーレイアウトを読み込み" },
        ["ResetUserLayout"] = new() { [PanoLanguage.Turkish]="Kullanıcı düzenini varsayılana döndür", [PanoLanguage.English]="Reset user layout to default", [PanoLanguage.German]="Benutzerlayout zurücksetzen", [PanoLanguage.French]="Réinitialiser la disposition utilisateur", [PanoLanguage.Spanish]="Restablecer diseño de usuario", [PanoLanguage.Italian]="Reimposta layout utente", [PanoLanguage.Russian]="Сбросить макет пользователя", [PanoLanguage.Arabic]="إعادة ضبط تخطيط المستخدم", [PanoLanguage.Chinese]="重置用户布局", [PanoLanguage.Japanese]="ユーザーレイアウトをリセット" },
        ["ExportUserLayout"] = new() { [PanoLanguage.Turkish]="Kullanıcı düzenini dışa aktar...", [PanoLanguage.English]="Export user layout...", [PanoLanguage.German]="Benutzerlayout exportieren...", [PanoLanguage.French]="Exporter la disposition utilisateur...", [PanoLanguage.Spanish]="Exportar diseño de usuario...", [PanoLanguage.Italian]="Esporta layout utente...", [PanoLanguage.Russian]="Экспорт макета пользователя...", [PanoLanguage.Arabic]="تصدير تخطيط المستخدم...", [PanoLanguage.Chinese]="导出用户布局...", [PanoLanguage.Japanese]="ユーザーレイアウトを書き出し..." },
        ["ImportUserLayout"] = new() { [PanoLanguage.Turkish]="Kullanıcı düzenini içe aktar...", [PanoLanguage.English]="Import user layout...", [PanoLanguage.German]="Benutzerlayout importieren...", [PanoLanguage.French]="Importer la disposition utilisateur...", [PanoLanguage.Spanish]="Importar diseño de usuario...", [PanoLanguage.Italian]="Importa layout utente...", [PanoLanguage.Russian]="Импорт макета пользователя...", [PanoLanguage.Arabic]="استيراد تخطيط المستخدم...", [PanoLanguage.Chinese]="导入用户布局...", [PanoLanguage.Japanese]="ユーザーレイアウトを読み込み..." },
        ["Grouping"] = new() { [PanoLanguage.Turkish]="Gruplama", [PanoLanguage.English]="Grouping", [PanoLanguage.German]="Gruppierung", [PanoLanguage.French]="Regroupement", [PanoLanguage.Spanish]="Agrupación", [PanoLanguage.Italian]="Raggruppamento", [PanoLanguage.Russian]="Группировка", [PanoLanguage.Arabic]="التجميع", [PanoLanguage.Chinese]="分组", [PanoLanguage.Japanese]="グループ化" },
        ["Freeze"] = new() { [PanoLanguage.Turkish]="Sabitleme", [PanoLanguage.English]="Freeze", [PanoLanguage.German]="Fixieren", [PanoLanguage.French]="Figer", [PanoLanguage.Spanish]="Fijar", [PanoLanguage.Italian]="Blocca", [PanoLanguage.Russian]="Закрепить", [PanoLanguage.Arabic]="تثبيت", [PanoLanguage.Chinese]="冻结", [PanoLanguage.Japanese]="固定" },
        ["View"] = new() { [PanoLanguage.Turkish]="Görünüm", [PanoLanguage.English]="View", [PanoLanguage.German]="Ansicht", [PanoLanguage.French]="Vue", [PanoLanguage.Spanish]="Vista", [PanoLanguage.Italian]="Vista", [PanoLanguage.Russian]="Вид", [PanoLanguage.Arabic]="العرض", [PanoLanguage.Chinese]="视图", [PanoLanguage.Japanese]="表示" },
        ["Clipboard"] = new() { [PanoLanguage.Turkish]="Pano", [PanoLanguage.English]="Clipboard", [PanoLanguage.German]="Zwischenablage", [PanoLanguage.French]="Presse-papiers", [PanoLanguage.Spanish]="Portapapeles", [PanoLanguage.Italian]="Appunti", [PanoLanguage.Russian]="Буфер обмена", [PanoLanguage.Arabic]="الحافظة", [PanoLanguage.Chinese]="剪贴板", [PanoLanguage.Japanese]="クリップボード" },
        ["Editing"] = new() { [PanoLanguage.Turkish]="Düzenleme", [PanoLanguage.English]="Editing", [PanoLanguage.German]="Bearbeiten", [PanoLanguage.French]="Édition", [PanoLanguage.Spanish]="Edición", [PanoLanguage.Italian]="Modifica", [PanoLanguage.Russian]="Редактирование", [PanoLanguage.Arabic]="التحرير", [PanoLanguage.Chinese]="编辑", [PanoLanguage.Japanese]="編集" },
        ["Analytics"] = new() { [PanoLanguage.Turkish]="Analiz", [PanoLanguage.English]="Analytics", [PanoLanguage.German]="Analyse", [PanoLanguage.French]="Analyse", [PanoLanguage.Spanish]="Análisis", [PanoLanguage.Italian]="Analisi", [PanoLanguage.Russian]="Аналитика", [PanoLanguage.Arabic]="التحليلات", [PanoLanguage.Chinese]="分析", [PanoLanguage.Japanese]="分析" },
        ["BuiltInHeaderMenu"] = new() { [PanoLanguage.Turkish]="Kolon / filtre özellikleri", [PanoLanguage.English]="Column / filter options", [PanoLanguage.German]="Spalten-/Filteroptionen", [PanoLanguage.French]="Options colonne / filtre", [PanoLanguage.Spanish]="Opciones de columna / filtro", [PanoLanguage.Italian]="Opzioni colonna / filtro", [PanoLanguage.Russian]="Параметры столбца / фильтра", [PanoLanguage.Arabic]="خيارات العمود / التصفية", [PanoLanguage.Chinese]="列 / 筛选选项", [PanoLanguage.Japanese]="列 / フィルターオプション" },
        ["PanoDataMode_Object"] = new() { [PanoLanguage.Turkish]="Nesne", [PanoLanguage.English]="Object", [PanoLanguage.German]="Objekt", [PanoLanguage.French]="Objet", [PanoLanguage.Spanish]="Objeto", [PanoLanguage.Italian]="Oggetto", [PanoLanguage.Russian]="Объект", [PanoLanguage.Arabic]="كائن", [PanoLanguage.Chinese]="对象", [PanoLanguage.Japanese]="オブジェクト" },
        ["PanoDataMode_DataTable"] = new() { [PanoLanguage.Turkish]="DataTable", [PanoLanguage.English]="DataTable", [PanoLanguage.German]="Datentabelle", [PanoLanguage.French]="Table de données", [PanoLanguage.Spanish]="Tabla de datos", [PanoLanguage.Italian]="Tabella dati", [PanoLanguage.Russian]="Таблица данных", [PanoLanguage.Arabic]="جدول بيانات", [PanoLanguage.Chinese]="数据表", [PanoLanguage.Japanese]="データテーブル" },
        ["PanoDataMode_Virtual"] = new() { [PanoLanguage.Turkish]="Sanal", [PanoLanguage.English]="Virtual", [PanoLanguage.German]="Virtuell", [PanoLanguage.French]="Virtuel", [PanoLanguage.Spanish]="Virtual", [PanoLanguage.Italian]="Virtuale", [PanoLanguage.Russian]="Виртуальный", [PanoLanguage.Arabic]="افتراضي", [PanoLanguage.Chinese]="虚拟", [PanoLanguage.Japanese]="仮想" },
        ["PanoDataMode_Tree"] = new() { [PanoLanguage.Turkish]="Ağaç", [PanoLanguage.English]="Tree", [PanoLanguage.German]="Baum", [PanoLanguage.French]="Arbre", [PanoLanguage.Spanish]="Árbol", [PanoLanguage.Italian]="Albero", [PanoLanguage.Russian]="Дерево", [PanoLanguage.Arabic]="شجرة", [PanoLanguage.Chinese]="树", [PanoLanguage.Japanese]="ツリー" },
        ["PanoDataMode_Tile"] = new() { [PanoLanguage.Turkish]="Kart", [PanoLanguage.English]="Tile", [PanoLanguage.German]="Kachel", [PanoLanguage.French]="Tuile", [PanoLanguage.Spanish]="Mosaico", [PanoLanguage.Italian]="Riquadro", [PanoLanguage.Russian]="Плитка", [PanoLanguage.Arabic]="بطاقة", [PanoLanguage.Chinese]="磁贴", [PanoLanguage.Japanese]="タイル" },
        ["Theme_System"] = new() { [PanoLanguage.Turkish]="Sistem", [PanoLanguage.English]="System", [PanoLanguage.German]="System", [PanoLanguage.French]="Système", [PanoLanguage.Spanish]="Sistema", [PanoLanguage.Italian]="Sistema", [PanoLanguage.Russian]="Система", [PanoLanguage.Arabic]="النظام", [PanoLanguage.Chinese]="系统", [PanoLanguage.Japanese]="システム" },
        ["Theme_Light"] = new() { [PanoLanguage.Turkish]="Açık", [PanoLanguage.English]="Light", [PanoLanguage.German]="Hell", [PanoLanguage.French]="Clair", [PanoLanguage.Spanish]="Claro", [PanoLanguage.Italian]="Chiaro", [PanoLanguage.Russian]="Светлая", [PanoLanguage.Arabic]="فاتح", [PanoLanguage.Chinese]="浅色", [PanoLanguage.Japanese]="ライト" },
        ["Theme_Dark"] = new() { [PanoLanguage.Turkish]="Koyu", [PanoLanguage.English]="Dark", [PanoLanguage.German]="Dunkel", [PanoLanguage.French]="Sombre", [PanoLanguage.Spanish]="Oscuro", [PanoLanguage.Italian]="Scuro", [PanoLanguage.Russian]="Темная", [PanoLanguage.Arabic]="داكن", [PanoLanguage.Chinese]="深色", [PanoLanguage.Japanese]="ダーク" },
        ["Theme_FluentLight"] = new() { [PanoLanguage.Turkish]="Fluent Açık", [PanoLanguage.English]="Fluent Light", [PanoLanguage.German]="Fluent Hell", [PanoLanguage.French]="Fluent clair", [PanoLanguage.Spanish]="Fluent claro", [PanoLanguage.Italian]="Fluent chiaro", [PanoLanguage.Russian]="Fluent светлая", [PanoLanguage.Arabic]="Fluent فاتح", [PanoLanguage.Chinese]="Fluent 浅色", [PanoLanguage.Japanese]="Fluent ライト" },
        ["Theme_FluentDark"] = new() { [PanoLanguage.Turkish]="Fluent Koyu", [PanoLanguage.English]="Fluent Dark", [PanoLanguage.German]="Fluent Dunkel", [PanoLanguage.French]="Fluent sombre", [PanoLanguage.Spanish]="Fluent oscuro", [PanoLanguage.Italian]="Fluent scuro", [PanoLanguage.Russian]="Fluent темная", [PanoLanguage.Arabic]="Fluent داكن", [PanoLanguage.Chinese]="Fluent 深色", [PanoLanguage.Japanese]="Fluent ダーク" },
        ["BuiltInMenuMergeText"] = new() { [PanoLanguage.Turkish]="Liste özellikleri", [PanoLanguage.English]="List options", [PanoLanguage.German]="Listenoptionen", [PanoLanguage.French]="Options de liste", [PanoLanguage.Spanish]="Opciones de lista", [PanoLanguage.Italian]="Opzioni elenco", [PanoLanguage.Russian]="Параметры списка", [PanoLanguage.Arabic]="خيارات القائمة", [PanoLanguage.Chinese]="列表选项", [PanoLanguage.Japanese]="リストオプション" },
        ["FastPreviewLimitedInfo"] = new() { [PanoLanguage.Turkish]="İlk açılış hızlı önizlemedir. 3+ karakter yazınca tüm veri kaynağı arka planda taranır.", [PanoLanguage.English]="First opening is a fast preview. Type 3+ characters to scan the full data source in the background.", [PanoLanguage.German]="Beim ersten Öffnen wird eine Schnellvorschau angezeigt. Ab 3 Zeichen wird die gesamte Datenquelle im Hintergrund durchsucht.", [PanoLanguage.French]="La première ouverture est un aperçu rapide. Tapez au moins 3 caractères pour analyser toute la source en arrière-plan.", [PanoLanguage.Spanish]="La primera apertura es una vista rápida. Escriba 3+ caracteres para buscar en toda la fuente en segundo plano.", [PanoLanguage.Italian]="La prima apertura è un'anteprima rapida. Digita almeno 3 caratteri per analizzare l'intera origine dati in background.", [PanoLanguage.Russian]="Первое открытие — быстрый предпросмотр. Введите 3+ символа, чтобы просканировать весь источник данных в фоне.", [PanoLanguage.Arabic]="الفتح الأول معاينة سريعة. اكتب 3 أحرف أو أكثر لفحص مصدر البيانات كاملاً في الخلفية.", [PanoLanguage.Chinese]="首次打开为快速预览。输入 3 个以上字符将在后台扫描完整数据源。", [PanoLanguage.Japanese]="初回表示は高速プレビューです。3文字以上入力すると全データソースをバックグラウンドで検索します。" },
        ["SearchingPreviewResults"] = new() { [PanoLanguage.Turkish]="Aranıyor... Liste ilk sonuçları gösteriyor", [PanoLanguage.English]="Searching... The list shows initial results", [PanoLanguage.German]="Suche läuft... Die Liste zeigt erste Ergebnisse", [PanoLanguage.French]="Recherche... La liste affiche les premiers résultats", [PanoLanguage.Spanish]="Buscando... La lista muestra los primeros resultados", [PanoLanguage.Italian]="Ricerca... L'elenco mostra i primi risultati", [PanoLanguage.Russian]="Поиск... список показывает первые результаты", [PanoLanguage.Arabic]="جارٍ البحث... تعرض القائمة النتائج الأولى", [PanoLanguage.Chinese]="正在搜索... 列表显示初始结果", [PanoLanguage.Japanese]="検索中... リストに初期結果を表示しています" },
        ["PrintPreviewSuffix"] = new() { [PanoLanguage.Turkish]="Önizleme", [PanoLanguage.English]="Preview", [PanoLanguage.German]="Vorschau", [PanoLanguage.French]="Aperçu", [PanoLanguage.Spanish]="Vista previa", [PanoLanguage.Italian]="Anteprima", [PanoLanguage.Russian]="Предпросмотр", [PanoLanguage.Arabic]="معاينة", [PanoLanguage.Chinese]="预览", [PanoLanguage.Japanese]="プレビュー" },
        ["Posters"] = new() { [PanoLanguage.Turkish]="Poster / Resimli içerik", [PanoLanguage.English]="Poster / Image content", [PanoLanguage.German]="Poster / Bildinhalt", [PanoLanguage.French]="Affiche / contenu image", [PanoLanguage.Spanish]="Póster / contenido visual", [PanoLanguage.Italian]="Poster / contenuto immagine", [PanoLanguage.Russian]="Постер / изображение", [PanoLanguage.Arabic]="ملصق / محتوى مرئي", [PanoLanguage.Chinese]="海报 / 图片内容", [PanoLanguage.Japanese]="ポスター / 画像コンテンツ" }
    };

    public static PanoLanguage Language { get; set; } = PanoLanguage.Auto;
    public static IDictionary<string, string> CustomTranslations { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

    public static string PanoDataModeName(string name)
    {
        string key = "PanoDataMode_" + name;
        string value = T(key);
        return string.Equals(value, key, StringComparison.OrdinalIgnoreCase) ? name : value;
    }

    public static string ThemePresetName(string name)
    {
        string key = "Theme_" + name;
        string value = T(key);
        return string.Equals(value, key, StringComparison.OrdinalIgnoreCase) ? name : value;
    }

    public static void LoadCustomTranslations(string jsonFilePath)
    {
        if (!File.Exists(jsonFilePath)) return;
        var data = JsonSerializer.Deserialize<Dictionary<string, string>>(File.ReadAllText(jsonFilePath));
        if (data == null) return;
        foreach (var kv in data) CustomTranslations[kv.Key] = kv.Value;
    }

    public static PanoLanguage EffectiveLanguage
    {
        get
        {
            if (Language != PanoLanguage.Auto) return Language;
            var two = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant();
            return two switch
            {
                "tr" => PanoLanguage.Turkish,
                "de" => PanoLanguage.German,
                "fr" => PanoLanguage.French,
                "es" => PanoLanguage.Spanish,
                "it" => PanoLanguage.Italian,
                "ru" => PanoLanguage.Russian,
                "ar" => PanoLanguage.Arabic,
                "zh" => PanoLanguage.Chinese,
                "ja" => PanoLanguage.Japanese,
                _ => PanoLanguage.English
            };
        }
    }

    public static string T(string key)
    {
        if (CustomTranslations.TryGetValue(key, out var custom)) return custom;
        if (!Texts.TryGetValue(key, out var perLang)) return key;
        var lang = EffectiveLanguage;
        if (perLang.TryGetValue(lang, out var value)) return value;
        return perLang.TryGetValue(PanoLanguage.English, out var en) ? en : key;
    }

    public static string Filtering => T("Filtering");
    public static string FilterWindow(string column) => $"'{column}' {T("FilterWindowSuffix")}";
    public static string FilterStyle => T("FilterStyle");
    public static string SortAscending => T("SortAscending");
    public static string SortDescending => T("SortDescending");
    public static string Unsort => T("Unsort");
    public static string ClearSort => T("ClearSort");
    public static string UnsortColumn => T("UnsortColumn");
    public static string FreezeColumn => T("FreezeColumn");
    public static string ClearFrozenColumns => T("ClearFrozenColumns");
    public static string AutoSizeColumn => T("AutoSizeColumn");
    public static string AutoSizeAllColumns => T("AutoSizeAllColumns");
    public static string GroupByColumn(string column) => $"{T("GroupByColumnPrefix")} {column}";
    public static string CollapseAllGroups => T("CollapseAllGroups");
    public static string ExpandAllGroups => T("ExpandAllGroups");
    public static string ClearGrouping => T("ClearGrouping");
    public static string CollapseThisGroup => T("CollapseThisGroup");
    public static string ExpandThisGroup => T("ExpandThisGroup");
    public static string ShowOnlyThisGroup => T("ShowOnlyThisGroup");
    public static string ViewMode => T("ViewMode");
    public static string ChooseColumns => T("ChooseColumns");
    public static string ClearFilters => T("ClearFilters");
    public static string ClearAllFilters => T("ClearAllFilters");
    public static string ColumnFilterTitle(string column) => $"{column} {T("ColumnFilterSuffix")}";
    public static string SearchPlaceholder => T("SearchPlaceholder");
    public static string ApplyTypedTextAsFilter => T("ApplyTypedTextAsFilter");
    public static string SearchTypedTextInColumn => T("SearchTypedTextInColumn");
    public static string SelectAll => T("SelectAll");
    public static string Apply => T("Apply");
    public static string Clear => T("Clear");
    public static string SeparateFilterWindow => T("SeparateFilterWindow");
    public static string EmptyList => T("EmptyList");
    public static string EmptyValue => T("EmptyValue");
    public static string Copy => T("Copy");
    public static string Paste => T("Paste");
    public static string EditCell => T("EditCell");
    public static string RowDetails => T("RowDetails");
    public static string PopupMenu => T("PopupMenu");
    public static string ModalWindow => T("ModalWindow");
    public static string Both => T("Both");
    public static string ExtraLarge => T("ExtraLarge");
    public static string Large => T("Large");
    public static string Medium => T("Medium");
    public static string List => T("List");
    public static string Details => T("Details");
    public static string Tiles => T("Tiles");
    public static string Posters => T("Posters");
    public static string Columns => T("Columns");
    public static string ShowAll => T("ShowAll");
    public static string HideAll => T("HideAll");
    public static string DefaultColumnLayout => T("DefaultColumnLayout");
    public static string FitVisibleColumns => T("FitVisibleColumns");
    public static string ColumnChooserWindow => T("ColumnChooserWindow");
    public static string ColumnSearchPlaceholder => T("ColumnSearchPlaceholder");
    public static string Cancel => T("Cancel");
    public static string ClearColumnFilter => T("ClearColumnFilter");
    public static string CopyCell => T("CopyCell");
    public static string CopySelectionJson => T("CopySelectionJson");
    public static string CopyMiniAnalytics => T("CopyMiniAnalytics");
    public static string Mode => T("Mode");
    public static string Theme => T("Theme");
    public static string Sorting => T("Sorting");
    public static string FrozenColumn => T("FrozenColumn");
    public static string ColumnWidth => T("ColumnWidth");
    public static string Layout => T("Layout");
    public static string SaveDefaultLayoutProfile => T("SaveDefaultLayoutProfile");
    public static string LayoutProfiles => T("LayoutProfiles");
    public static string SaveUserLayout => T("SaveUserLayout");
    public static string LoadUserLayout => T("LoadUserLayout");
    public static string ResetUserLayout => T("ResetUserLayout");
    public static string ExportUserLayout => T("ExportUserLayout");
    public static string ImportUserLayout => T("ImportUserLayout");
    public static string Grouping => T("Grouping");
    public static string Freeze => T("Freeze");
    public static string View => T("View");
    public static string Clipboard => T("Clipboard");
    public static string Editing => T("Editing");
    public static string Analytics => T("Analytics");
    public static string BuiltInHeaderMenu => T("BuiltInHeaderMenu");
    public static string BuiltInMenuMergeText => T("BuiltInMenuMergeText");
    public static string FastPreviewLimitedInfo => T("FastPreviewLimitedInfo");
    public static string SearchingPreviewResults => T("SearchingPreviewResults");
    public static string PrintPreviewSuffix => T("PrintPreviewSuffix");

    public static string SaveColumnLayout => T("SaveColumnLayout");
    public static string LoadColumnLayout => T("LoadColumnLayout");
    public static string ResetColumnLayout => T("ResetColumnLayout");
    public static string ColumnChooserTitle => T("ColumnChooserTitle");
    public static string OK => T("OK");
    public static string FastPreviewInfo => T("FastPreviewInfo");
}

