using System.Globalization;
using System.Text.Json;

namespace ViewGrid.Localization;

public static class ViewGridText
{
    private static readonly Dictionary<string, Dictionary<ViewGridLanguage, string>> Texts = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Filtering"] = new() { [ViewGridLanguage.Turkish]="Filtreleme", [ViewGridLanguage.English]="Filtering", [ViewGridLanguage.German]="Filtern", [ViewGridLanguage.French]="Filtrage", [ViewGridLanguage.Spanish]="Filtrado", [ViewGridLanguage.Italian]="Filtro", [ViewGridLanguage.Russian]="Фильтр", [ViewGridLanguage.Arabic]="تصفية", [ViewGridLanguage.Chinese]="筛选", [ViewGridLanguage.Japanese]="フィルター" },
        ["FilterStyle"] = new() { [ViewGridLanguage.Turkish]="Filtre stili", [ViewGridLanguage.English]="Filter style", [ViewGridLanguage.German]="Filterstil", [ViewGridLanguage.French]="Style de filtre", [ViewGridLanguage.Spanish]="Estilo de filtro", [ViewGridLanguage.Italian]="Stile filtro", [ViewGridLanguage.Russian]="Стиль фильтра", [ViewGridLanguage.Arabic]="نمط التصفية", [ViewGridLanguage.Chinese]="筛选样式", [ViewGridLanguage.Japanese]="フィルター形式" },
        ["SortAscending"] = new() { [ViewGridLanguage.Turkish]="Artan sırala", [ViewGridLanguage.English]="Sort ascending", [ViewGridLanguage.German]="Aufsteigend sortieren", [ViewGridLanguage.French]="Tri croissant", [ViewGridLanguage.Spanish]="Orden ascendente", [ViewGridLanguage.Italian]="Ordina crescente", [ViewGridLanguage.Russian]="По возрастанию", [ViewGridLanguage.Arabic]="ترتيب تصاعدي", [ViewGridLanguage.Chinese]="升序排序", [ViewGridLanguage.Japanese]="昇順で並べ替え" },
        ["SortDescending"] = new() { [ViewGridLanguage.Turkish]="Azalan sırala", [ViewGridLanguage.English]="Sort descending", [ViewGridLanguage.German]="Absteigend sortieren", [ViewGridLanguage.French]="Tri décroissant", [ViewGridLanguage.Spanish]="Orden descendente", [ViewGridLanguage.Italian]="Ordina decrescente", [ViewGridLanguage.Russian]="По убыванию", [ViewGridLanguage.Arabic]="ترتيب تنازلي", [ViewGridLanguage.Chinese]="降序排序", [ViewGridLanguage.Japanese]="降順で並べ替え" },
        ["Unsort"] = new() { [ViewGridLanguage.Turkish]="Sıralamayı kaldır", [ViewGridLanguage.English]="Unsort", [ViewGridLanguage.German]="Sortierung entfernen", [ViewGridLanguage.French]="Annuler le tri", [ViewGridLanguage.Spanish]="Quitar orden", [ViewGridLanguage.Italian]="Rimuovi ordinamento", [ViewGridLanguage.Russian]="Без сортировки", [ViewGridLanguage.Arabic]="إزالة الترتيب", [ViewGridLanguage.Chinese]="取消排序", [ViewGridLanguage.Japanese]="並べ替え解除" },
        ["ClearSort"] = new() { [ViewGridLanguage.Turkish]="Tüm sıralamayı temizle / default sıraya dön", [ViewGridLanguage.English]="Clear all sorting / return to default order", [ViewGridLanguage.German]="Alle Sortierungen löschen / Standardreihenfolge", [ViewGridLanguage.French]="Effacer tous les tris / ordre par défaut", [ViewGridLanguage.Spanish]="Borrar orden / volver al orden inicial", [ViewGridLanguage.Italian]="Cancella ordinamento / ordine predefinito", [ViewGridLanguage.Russian]="Очистить сортировку / порядок по умолчанию", [ViewGridLanguage.Arabic]="مسح الترتيب / العودة للوضع الافتراضي", [ViewGridLanguage.Chinese]="清除排序 / 恢复默认顺序", [ViewGridLanguage.Japanese]="すべての並べ替えを解除 / 既定順へ" },
        ["UnsortColumn"] = new() { [ViewGridLanguage.Turkish]="Bu kolonu unsort yap", [ViewGridLanguage.English]="Unsort this column", [ViewGridLanguage.German]="Diese Spalte unsortieren", [ViewGridLanguage.French]="Annuler le tri de cette colonne", [ViewGridLanguage.Spanish]="Quitar orden de esta columna", [ViewGridLanguage.Italian]="Rimuovi ordinamento colonna", [ViewGridLanguage.Russian]="Убрать сортировку столбца", [ViewGridLanguage.Arabic]="إزالة ترتيب هذا العمود", [ViewGridLanguage.Chinese]="取消此列排序", [ViewGridLanguage.Japanese]="この列の並べ替えを解除" },
        ["FreezeColumn"] = new() { [ViewGridLanguage.Turkish]="Bu kolonu sabitle", [ViewGridLanguage.English]="Freeze this column", [ViewGridLanguage.German]="Diese Spalte fixieren", [ViewGridLanguage.French]="Figer cette colonne", [ViewGridLanguage.Spanish]="Fijar esta columna", [ViewGridLanguage.Italian]="Blocca questa colonna", [ViewGridLanguage.Russian]="Закрепить столбец", [ViewGridLanguage.Arabic]="تثبيت هذا العمود", [ViewGridLanguage.Chinese]="冻结此列", [ViewGridLanguage.Japanese]="この列を固定" },
        ["ClearFrozenColumns"] = new() { [ViewGridLanguage.Turkish]="Sabit kolonları kaldır", [ViewGridLanguage.English]="Clear frozen columns", [ViewGridLanguage.German]="Fixierte Spalten lösen", [ViewGridLanguage.French]="Libérer les colonnes figées", [ViewGridLanguage.Spanish]="Quitar columnas fijadas", [ViewGridLanguage.Italian]="Sblocca colonne", [ViewGridLanguage.Russian]="Снять закрепление", [ViewGridLanguage.Arabic]="إلغاء تثبيت الأعمدة", [ViewGridLanguage.Chinese]="取消冻结列", [ViewGridLanguage.Japanese]="固定列を解除" },
        ["AutoSizeColumn"] = new() { [ViewGridLanguage.Turkish]="Kolon genişliğini otomatik ayarla", [ViewGridLanguage.English]="Auto size column", [ViewGridLanguage.German]="Spaltenbreite automatisch", [ViewGridLanguage.French]="Ajuster la colonne", [ViewGridLanguage.Spanish]="Autoajustar columna", [ViewGridLanguage.Italian]="Adatta colonna", [ViewGridLanguage.Russian]="Автоширина столбца", [ViewGridLanguage.Arabic]="ضبط عرض العمود تلقائياً", [ViewGridLanguage.Chinese]="自动调整列宽", [ViewGridLanguage.Japanese]="列幅を自動調整" },
        ["AutoSizeAllColumns"] = new() { [ViewGridLanguage.Turkish]="Tüm kolonları otomatik sığdır", [ViewGridLanguage.English]="Auto size all columns", [ViewGridLanguage.German]="Alle Spalten automatisch anpassen", [ViewGridLanguage.French]="Ajuster toutes les colonnes", [ViewGridLanguage.Spanish]="Autoajustar todas las columnas", [ViewGridLanguage.Italian]="Adatta tutte le colonne", [ViewGridLanguage.Russian]="Автоширина всех столбцов", [ViewGridLanguage.Arabic]="ضبط كل الأعمدة تلقائياً", [ViewGridLanguage.Chinese]="自动调整所有列", [ViewGridLanguage.Japanese]="すべての列幅を自動調整" },
        ["SaveColumnLayout"] = new() { [ViewGridLanguage.Turkish]="Kolon düzenini kaydet", [ViewGridLanguage.English]="Save column layout", [ViewGridLanguage.German]="Spaltenlayout speichern", [ViewGridLanguage.French]="Enregistrer la disposition", [ViewGridLanguage.Spanish]="Guardar diseño de columnas", [ViewGridLanguage.Italian]="Salva layout colonne", [ViewGridLanguage.Russian]="Сохранить порядок столбцов", [ViewGridLanguage.Arabic]="حفظ تخطيط الأعمدة", [ViewGridLanguage.Chinese]="保存列布局", [ViewGridLanguage.Japanese]="列レイアウトを保存" },
        ["LoadColumnLayout"] = new() { [ViewGridLanguage.Turkish]="Kolon düzenini yükle", [ViewGridLanguage.English]="Load column layout", [ViewGridLanguage.German]="Spaltenlayout laden", [ViewGridLanguage.French]="Charger la disposition", [ViewGridLanguage.Spanish]="Cargar diseño de columnas", [ViewGridLanguage.Italian]="Carica layout colonne", [ViewGridLanguage.Russian]="Загрузить порядок столбцов", [ViewGridLanguage.Arabic]="تحميل تخطيط الأعمدة", [ViewGridLanguage.Chinese]="加载列布局", [ViewGridLanguage.Japanese]="列レイアウトを読み込み" },
        ["ResetColumnLayout"] = new() { [ViewGridLanguage.Turkish]="Kolon düzenini sıfırla", [ViewGridLanguage.English]="Reset column layout", [ViewGridLanguage.German]="Spaltenlayout zurücksetzen", [ViewGridLanguage.French]="Réinitialiser la disposition", [ViewGridLanguage.Spanish]="Restablecer diseño de columnas", [ViewGridLanguage.Italian]="Reimposta layout colonne", [ViewGridLanguage.Russian]="Сбросить порядок столбцов", [ViewGridLanguage.Arabic]="إعادة ضبط تخطيط الأعمدة", [ViewGridLanguage.Chinese]="重置列布局", [ViewGridLanguage.Japanese]="列レイアウトをリセット" },
        ["ColumnChooserTitle"] = new() { [ViewGridLanguage.Turkish]="Kolon Seçici", [ViewGridLanguage.English]="Column chooser", [ViewGridLanguage.German]="Spaltenauswahl", [ViewGridLanguage.French]="Sélecteur de colonnes", [ViewGridLanguage.Spanish]="Selector de columnas", [ViewGridLanguage.Italian]="Selettore colonne", [ViewGridLanguage.Russian]="Выбор столбцов", [ViewGridLanguage.Arabic]="اختيار الأعمدة", [ViewGridLanguage.Chinese]="列选择器", [ViewGridLanguage.Japanese]="列の選択" },
        ["OK"] = new() { [ViewGridLanguage.Turkish]="Tamam", [ViewGridLanguage.English]="OK", [ViewGridLanguage.German]="OK", [ViewGridLanguage.French]="OK", [ViewGridLanguage.Spanish]="Aceptar", [ViewGridLanguage.Italian]="OK", [ViewGridLanguage.Russian]="OK", [ViewGridLanguage.Arabic]="موافق", [ViewGridLanguage.Chinese]="确定", [ViewGridLanguage.Japanese]="OK" },
        ["FastPreviewInfo"] = new() { [ViewGridLanguage.Turkish]="Hızlı önizleme; yazılan filtre tüm kayıtlara uygulanır.", [ViewGridLanguage.English]="Fast preview; typed filter applies to all rows.", [ViewGridLanguage.German]="Schnellvorschau; Textfilter gilt für alle Zeilen.", [ViewGridLanguage.French]="Aperçu rapide ; le texte filtre toutes les lignes.", [ViewGridLanguage.Spanish]="Vista rápida; el texto filtra todas las filas.", [ViewGridLanguage.Italian]="Anteprima rapida; il testo filtra tutte le righe.", [ViewGridLanguage.Russian]="Быстрый просмотр; текстовый фильтр применяется ко всем строкам.", [ViewGridLanguage.Arabic]="معاينة سريعة؛ النص يصفّي كل الصفوف.", [ViewGridLanguage.Chinese]="快速预览；输入筛选应用于所有行。", [ViewGridLanguage.Japanese]="高速プレビュー。入力フィルターは全行に適用。" },
        ["GroupByColumnPrefix"] = new() { [ViewGridLanguage.Turkish]="Bu kolona göre grupla:", [ViewGridLanguage.English]="Group by this column:", [ViewGridLanguage.German]="Nach dieser Spalte gruppieren:", [ViewGridLanguage.French]="Regrouper par cette colonne :", [ViewGridLanguage.Spanish]="Agrupar por esta columna:", [ViewGridLanguage.Italian]="Raggruppa per questa colonna:", [ViewGridLanguage.Russian]="Группировать по столбцу:", [ViewGridLanguage.Arabic]="تجميع حسب هذا العمود:", [ViewGridLanguage.Chinese]="按此列分组:", [ViewGridLanguage.Japanese]="この列でグループ化:" },
        ["CollapseAllGroups"] = new() { [ViewGridLanguage.Turkish]="Tüm grupları daralt", [ViewGridLanguage.English]="Collapse all groups", [ViewGridLanguage.German]="Alle Gruppen einklappen", [ViewGridLanguage.French]="Réduire tous les groupes", [ViewGridLanguage.Spanish]="Contraer todos los grupos", [ViewGridLanguage.Italian]="Comprimi tutti i gruppi", [ViewGridLanguage.Russian]="Свернуть группы", [ViewGridLanguage.Arabic]="طي كل المجموعات", [ViewGridLanguage.Chinese]="折叠所有分组", [ViewGridLanguage.Japanese]="すべてのグループを折りたたむ" },
        ["ExpandAllGroups"] = new() { [ViewGridLanguage.Turkish]="Tüm grupları aç", [ViewGridLanguage.English]="Expand all groups", [ViewGridLanguage.German]="Alle Gruppen ausklappen", [ViewGridLanguage.French]="Développer tous les groupes", [ViewGridLanguage.Spanish]="Expandir todos los grupos", [ViewGridLanguage.Italian]="Espandi tutti i gruppi", [ViewGridLanguage.Russian]="Развернуть группы", [ViewGridLanguage.Arabic]="فتح كل المجموعات", [ViewGridLanguage.Chinese]="展开所有分组", [ViewGridLanguage.Japanese]="すべてのグループを展開" },
        ["ClearGrouping"] = new() { [ViewGridLanguage.Turkish]="Gruplamayı kaldır", [ViewGridLanguage.English]="Clear grouping", [ViewGridLanguage.German]="Gruppierung entfernen", [ViewGridLanguage.French]="Effacer le regroupement", [ViewGridLanguage.Spanish]="Quitar agrupación", [ViewGridLanguage.Italian]="Rimuovi raggruppamento", [ViewGridLanguage.Russian]="Убрать группировку", [ViewGridLanguage.Arabic]="إزالة التجميع", [ViewGridLanguage.Chinese]="清除分组", [ViewGridLanguage.Japanese]="グループ化を解除" },
        ["CollapseThisGroup"] = new() { [ViewGridLanguage.Turkish]="Bu grubu daralt", [ViewGridLanguage.English]="Collapse this group", [ViewGridLanguage.German]="Diese Gruppe einklappen", [ViewGridLanguage.French]="Réduire ce groupe", [ViewGridLanguage.Spanish]="Contraer este grupo", [ViewGridLanguage.Italian]="Comprimi questo gruppo", [ViewGridLanguage.Russian]="Свернуть эту группу", [ViewGridLanguage.Arabic]="طي هذه المجموعة", [ViewGridLanguage.Chinese]="折叠此分组", [ViewGridLanguage.Japanese]="このグループを折りたたむ" },
        ["ExpandThisGroup"] = new() { [ViewGridLanguage.Turkish]="Bu grubu aç", [ViewGridLanguage.English]="Expand this group", [ViewGridLanguage.German]="Diese Gruppe ausklappen", [ViewGridLanguage.French]="Développer ce groupe", [ViewGridLanguage.Spanish]="Expandir este grupo", [ViewGridLanguage.Italian]="Espandi questo gruppo", [ViewGridLanguage.Russian]="Развернуть эту группу", [ViewGridLanguage.Arabic]="فتح هذه المجموعة", [ViewGridLanguage.Chinese]="展开此分组", [ViewGridLanguage.Japanese]="このグループを展開" },
        ["ShowOnlyThisGroup"] = new() { [ViewGridLanguage.Turkish]="Sadece bu grubu açık bırak", [ViewGridLanguage.English]="Keep only this group open", [ViewGridLanguage.German]="Nur diese Gruppe offen lassen", [ViewGridLanguage.French]="Garder seulement ce groupe ouvert", [ViewGridLanguage.Spanish]="Dejar abierto solo este grupo", [ViewGridLanguage.Italian]="Lascia aperto solo questo gruppo", [ViewGridLanguage.Russian]="Оставить открытой только эту группу", [ViewGridLanguage.Arabic]="إبقاء هذه المجموعة فقط مفتوحة", [ViewGridLanguage.Chinese]="仅保持此分组展开", [ViewGridLanguage.Japanese]="このグループだけ開いたままにする" },
        ["ViewMode"] = new() { [ViewGridLanguage.Turkish]="Görünüm modu", [ViewGridLanguage.English]="View mode", [ViewGridLanguage.German]="Ansichtsmodus", [ViewGridLanguage.French]="Mode d'affichage", [ViewGridLanguage.Spanish]="Modo de vista", [ViewGridLanguage.Italian]="Modalità vista", [ViewGridLanguage.Russian]="Режим просмотра", [ViewGridLanguage.Arabic]="نمط العرض", [ViewGridLanguage.Chinese]="视图模式", [ViewGridLanguage.Japanese]="表示モード" },
        ["ChooseColumns"] = new() { [ViewGridLanguage.Turkish]="Kolonları seç...", [ViewGridLanguage.English]="Choose columns...", [ViewGridLanguage.German]="Spalten wählen...", [ViewGridLanguage.French]="Choisir les colonnes...", [ViewGridLanguage.Spanish]="Elegir columnas...", [ViewGridLanguage.Italian]="Scegli colonne...", [ViewGridLanguage.Russian]="Выбрать столбцы...", [ViewGridLanguage.Arabic]="اختيار الأعمدة...", [ViewGridLanguage.Chinese]="选择列...", [ViewGridLanguage.Japanese]="列を選択..." },
        ["ClearFilters"] = new() { [ViewGridLanguage.Turkish]="Filtreleri Temizle", [ViewGridLanguage.English]="Clear Filters", [ViewGridLanguage.German]="Filter löschen", [ViewGridLanguage.French]="Effacer les filtres", [ViewGridLanguage.Spanish]="Borrar filtros", [ViewGridLanguage.Italian]="Cancella filtri", [ViewGridLanguage.Russian]="Очистить фильтры", [ViewGridLanguage.Arabic]="مسح عوامل التصفية", [ViewGridLanguage.Chinese]="清除筛选", [ViewGridLanguage.Japanese]="フィルターをクリア" },
        ["ClearAllFilters"] = new() { [ViewGridLanguage.Turkish]="Tüm filtreleri temizle", [ViewGridLanguage.English]="Clear all filters", [ViewGridLanguage.German]="Alle Filter löschen", [ViewGridLanguage.French]="Effacer tous les filtres", [ViewGridLanguage.Spanish]="Borrar todos los filtros", [ViewGridLanguage.Italian]="Cancella tutti i filtri", [ViewGridLanguage.Russian]="Очистить все фильтры", [ViewGridLanguage.Arabic]="مسح كل عوامل التصفية", [ViewGridLanguage.Chinese]="清除所有筛选", [ViewGridLanguage.Japanese]="すべてのフィルターをクリア" },
        ["SearchPlaceholder"] = new() { [ViewGridLanguage.Turkish]="Aranacak / filtrelenecek değer...", [ViewGridLanguage.English]="Search / filter value...", [ViewGridLanguage.German]="Such-/Filterwert...", [ViewGridLanguage.French]="Valeur à rechercher / filtrer...", [ViewGridLanguage.Spanish]="Valor a buscar / filtrar...", [ViewGridLanguage.Italian]="Valore da cercare / filtrare...", [ViewGridLanguage.Russian]="Поиск / значение фильтра...", [ViewGridLanguage.Arabic]="قيمة البحث / التصفية...", [ViewGridLanguage.Chinese]="搜索 / 筛选值...", [ViewGridLanguage.Japanese]="検索 / フィルター値..." },
        ["ApplyTypedTextAsFilter"] = new() { [ViewGridLanguage.Turkish]="Yazılan metni filtre olarak uygula", [ViewGridLanguage.English]="Apply typed text as filter", [ViewGridLanguage.German]="Eingabetext als Filter verwenden", [ViewGridLanguage.French]="Appliquer le texte saisi comme filtre", [ViewGridLanguage.Spanish]="Aplicar texto escrito como filtro", [ViewGridLanguage.Italian]="Usa il testo come filtro", [ViewGridLanguage.Russian]="Применить введенный текст", [ViewGridLanguage.Arabic]="تطبيق النص المكتوب كتصفية", [ViewGridLanguage.Chinese]="将输入文本作为筛选", [ViewGridLanguage.Japanese]="入力テキストをフィルターに適用" },
        ["SearchTypedTextInColumn"] = new() { [ViewGridLanguage.Turkish]="Yazılan metni kolonda ara", [ViewGridLanguage.English]="Search typed text in column", [ViewGridLanguage.German]="Text in Spalte suchen", [ViewGridLanguage.French]="Chercher le texte dans la colonne", [ViewGridLanguage.Spanish]="Buscar texto en la columna", [ViewGridLanguage.Italian]="Cerca testo nella colonna", [ViewGridLanguage.Russian]="Искать текст в столбце", [ViewGridLanguage.Arabic]="البحث عن النص في العمود", [ViewGridLanguage.Chinese]="在列中搜索输入文本", [ViewGridLanguage.Japanese]="列内で入力テキストを検索" },
        ["SelectAll"] = new() { [ViewGridLanguage.Turkish]="Tümünü seç", [ViewGridLanguage.English]="Select All", [ViewGridLanguage.German]="Alle auswählen", [ViewGridLanguage.French]="Tout sélectionner", [ViewGridLanguage.Spanish]="Seleccionar todo", [ViewGridLanguage.Italian]="Seleziona tutto", [ViewGridLanguage.Russian]="Выбрать все", [ViewGridLanguage.Arabic]="تحديد الكل", [ViewGridLanguage.Chinese]="全选", [ViewGridLanguage.Japanese]="すべて選択" },
        ["Apply"] = new() { [ViewGridLanguage.Turkish]="Uygula", [ViewGridLanguage.English]="Apply", [ViewGridLanguage.German]="Anwenden", [ViewGridLanguage.French]="Appliquer", [ViewGridLanguage.Spanish]="Aplicar", [ViewGridLanguage.Italian]="Applica", [ViewGridLanguage.Russian]="Применить", [ViewGridLanguage.Arabic]="تطبيق", [ViewGridLanguage.Chinese]="应用", [ViewGridLanguage.Japanese]="適用" },
        ["Clear"] = new() { [ViewGridLanguage.Turkish]="Temizle", [ViewGridLanguage.English]="Clear", [ViewGridLanguage.German]="Löschen", [ViewGridLanguage.French]="Effacer", [ViewGridLanguage.Spanish]="Limpiar", [ViewGridLanguage.Italian]="Cancella", [ViewGridLanguage.Russian]="Очистить", [ViewGridLanguage.Arabic]="مسح", [ViewGridLanguage.Chinese]="清除", [ViewGridLanguage.Japanese]="クリア" },
        ["SeparateFilterWindow"] = new() { [ViewGridLanguage.Turkish]="Ayrı filtre penceresi...", [ViewGridLanguage.English]="Separate filter window...", [ViewGridLanguage.German]="Separates Filterfenster...", [ViewGridLanguage.French]="Fenêtre de filtre séparée...", [ViewGridLanguage.Spanish]="Ventana de filtro separada...", [ViewGridLanguage.Italian]="Finestra filtro separata...", [ViewGridLanguage.Russian]="Отдельное окно фильтра...", [ViewGridLanguage.Arabic]="نافذة تصفية منفصلة...", [ViewGridLanguage.Chinese]="单独筛选窗口...", [ViewGridLanguage.Japanese]="別のフィルターウィンドウ..." },
        ["EmptyList"] = new() { [ViewGridLanguage.Turkish]="Liste boş", [ViewGridLanguage.English]="List is empty", [ViewGridLanguage.German]="Liste ist leer", [ViewGridLanguage.French]="La liste est vide", [ViewGridLanguage.Spanish]="La lista está vacía", [ViewGridLanguage.Italian]="La lista è vuota", [ViewGridLanguage.Russian]="Список пуст", [ViewGridLanguage.Arabic]="القائمة فارغة", [ViewGridLanguage.Chinese]="列表为空", [ViewGridLanguage.Japanese]="リストは空です" },

        ["ColumnFilterSuffix"] = new() { [ViewGridLanguage.Turkish]="filtresi", [ViewGridLanguage.English]="filter", [ViewGridLanguage.German]="Filter", [ViewGridLanguage.French]="filtre", [ViewGridLanguage.Spanish]="filtro", [ViewGridLanguage.Italian]="filtro", [ViewGridLanguage.Russian]="фильтр", [ViewGridLanguage.Arabic]="تصفية", [ViewGridLanguage.Chinese]="筛选", [ViewGridLanguage.Japanese]="フィルター" },
        ["FilterWindowSuffix"] = new() { [ViewGridLanguage.Turkish]="filtre penceresi...", [ViewGridLanguage.English]="filter window...", [ViewGridLanguage.German]="Filterfenster...", [ViewGridLanguage.French]="fenêtre de filtre...", [ViewGridLanguage.Spanish]="ventana de filtro...", [ViewGridLanguage.Italian]="finestra filtro...", [ViewGridLanguage.Russian]="окно фильтра...", [ViewGridLanguage.Arabic]="نافذة التصفية...", [ViewGridLanguage.Chinese]="筛选窗口...", [ViewGridLanguage.Japanese]="フィルターウィンドウ..." },
        ["EmptyValue"] = new() { [ViewGridLanguage.Turkish]="(Boş)", [ViewGridLanguage.English]="(Empty)", [ViewGridLanguage.German]="(Leer)", [ViewGridLanguage.French]="(Vide)", [ViewGridLanguage.Spanish]="(Vacío)", [ViewGridLanguage.Italian]="(Vuoto)", [ViewGridLanguage.Russian]="(Пусто)", [ViewGridLanguage.Arabic]="(فارغ)", [ViewGridLanguage.Chinese]="(空)", [ViewGridLanguage.Japanese]="(空)" },
        ["Copy"] = new() { [ViewGridLanguage.Turkish]="Kopyala", [ViewGridLanguage.English]="Copy", [ViewGridLanguage.German]="Kopieren", [ViewGridLanguage.French]="Copier", [ViewGridLanguage.Spanish]="Copiar", [ViewGridLanguage.Italian]="Copia", [ViewGridLanguage.Russian]="Копировать", [ViewGridLanguage.Arabic]="نسخ", [ViewGridLanguage.Chinese]="复制", [ViewGridLanguage.Japanese]="コピー" },
        ["Paste"] = new() { [ViewGridLanguage.Turkish]="Yapıştır", [ViewGridLanguage.English]="Paste", [ViewGridLanguage.German]="Einfügen", [ViewGridLanguage.French]="Coller", [ViewGridLanguage.Spanish]="Pegar", [ViewGridLanguage.Italian]="Incolla", [ViewGridLanguage.Russian]="Вставить", [ViewGridLanguage.Arabic]="لصق", [ViewGridLanguage.Chinese]="粘贴", [ViewGridLanguage.Japanese]="貼り付け" },
        ["EditCell"] = new() { [ViewGridLanguage.Turkish]="Hücreyi Düzenle", [ViewGridLanguage.English]="Edit cell", [ViewGridLanguage.German]="Zelle bearbeiten", [ViewGridLanguage.French]="Modifier la cellule", [ViewGridLanguage.Spanish]="Editar celda", [ViewGridLanguage.Italian]="Modifica cella", [ViewGridLanguage.Russian]="Редактировать ячейку", [ViewGridLanguage.Arabic]="تحرير الخلية", [ViewGridLanguage.Chinese]="编辑单元格", [ViewGridLanguage.Japanese]="セルを編集" },
        ["RowDetails"] = new() { [ViewGridLanguage.Turkish]="Satır Detayı", [ViewGridLanguage.English]="Row details", [ViewGridLanguage.German]="Zeilendetails", [ViewGridLanguage.French]="Détails de ligne", [ViewGridLanguage.Spanish]="Detalles de fila", [ViewGridLanguage.Italian]="Dettagli riga", [ViewGridLanguage.Russian]="Детали строки", [ViewGridLanguage.Arabic]="تفاصيل الصف", [ViewGridLanguage.Chinese]="行详情", [ViewGridLanguage.Japanese]="行の詳細" },
        ["PopupMenu"] = new() { [ViewGridLanguage.Turkish]="Popup menü", [ViewGridLanguage.English]="Popup menu", [ViewGridLanguage.German]="Popup-Menü", [ViewGridLanguage.French]="Menu popup", [ViewGridLanguage.Spanish]="Menú emergente", [ViewGridLanguage.Italian]="Menu popup", [ViewGridLanguage.Russian]="Всплывающее меню", [ViewGridLanguage.Arabic]="قائمة منبثقة", [ViewGridLanguage.Chinese]="弹出菜单", [ViewGridLanguage.Japanese]="ポップアップメニュー" },
        ["ModalWindow"] = new() { [ViewGridLanguage.Turkish]="Ayrı pencere", [ViewGridLanguage.English]="Separate window", [ViewGridLanguage.German]="Separates Fenster", [ViewGridLanguage.French]="Fenêtre séparée", [ViewGridLanguage.Spanish]="Ventana separada", [ViewGridLanguage.Italian]="Finestra separata", [ViewGridLanguage.Russian]="Отдельное окно", [ViewGridLanguage.Arabic]="نافذة منفصلة", [ViewGridLanguage.Chinese]="独立窗口", [ViewGridLanguage.Japanese]="別ウィンドウ" },
        ["Both"] = new() { [ViewGridLanguage.Turkish]="İkisi birlikte", [ViewGridLanguage.English]="Both", [ViewGridLanguage.German]="Beide", [ViewGridLanguage.French]="Les deux", [ViewGridLanguage.Spanish]="Ambos", [ViewGridLanguage.Italian]="Entrambi", [ViewGridLanguage.Russian]="Оба", [ViewGridLanguage.Arabic]="كلاهما", [ViewGridLanguage.Chinese]="两者", [ViewGridLanguage.Japanese]="両方" },
        ["ExtraLarge"] = new() { [ViewGridLanguage.Turkish]="Kompakt", [ViewGridLanguage.English]="Extra large", [ViewGridLanguage.German]="Sehr groß", [ViewGridLanguage.French]="Très grand", [ViewGridLanguage.Spanish]="Muy grande", [ViewGridLanguage.Italian]="Molto grande", [ViewGridLanguage.Russian]="Очень крупный", [ViewGridLanguage.Arabic]="كبير جداً", [ViewGridLanguage.Chinese]="超大", [ViewGridLanguage.Japanese]="特大" },
        ["Large"] = new() { [ViewGridLanguage.Turkish]="Standart", [ViewGridLanguage.English]="Large", [ViewGridLanguage.German]="Groß", [ViewGridLanguage.French]="Grand", [ViewGridLanguage.Spanish]="Grande", [ViewGridLanguage.Italian]="Grande", [ViewGridLanguage.Russian]="Крупный", [ViewGridLanguage.Arabic]="كبير", [ViewGridLanguage.Chinese]="大", [ViewGridLanguage.Japanese]="大" },
        ["Medium"] = new() { [ViewGridLanguage.Turkish]="Geniş", [ViewGridLanguage.English]="Medium", [ViewGridLanguage.German]="Mittel", [ViewGridLanguage.French]="Moyen", [ViewGridLanguage.Spanish]="Medio", [ViewGridLanguage.Italian]="Medio", [ViewGridLanguage.Russian]="Средний", [ViewGridLanguage.Arabic]="متوسط", [ViewGridLanguage.Chinese]="中", [ViewGridLanguage.Japanese]="中" },
        ["List"] = new() { [ViewGridLanguage.Turkish]="Liste", [ViewGridLanguage.English]="List", [ViewGridLanguage.German]="Liste", [ViewGridLanguage.French]="Liste", [ViewGridLanguage.Spanish]="Lista", [ViewGridLanguage.Italian]="Lista", [ViewGridLanguage.Russian]="Список", [ViewGridLanguage.Arabic]="قائمة", [ViewGridLanguage.Chinese]="列表", [ViewGridLanguage.Japanese]="リスト" },
        ["Details"] = new() { [ViewGridLanguage.Turkish]="Detay", [ViewGridLanguage.English]="Details", [ViewGridLanguage.German]="Details", [ViewGridLanguage.French]="Détails", [ViewGridLanguage.Spanish]="Detalles", [ViewGridLanguage.Italian]="Dettagli", [ViewGridLanguage.Russian]="Подробности", [ViewGridLanguage.Arabic]="تفاصيل", [ViewGridLanguage.Chinese]="详细信息", [ViewGridLanguage.Japanese]="詳細" },
        ["Tiles"] = new() { [ViewGridLanguage.Turkish]="Kart", [ViewGridLanguage.English]="Tile / Card", [ViewGridLanguage.German]="Kachel / Karte", [ViewGridLanguage.French]="Tuile / Carte", [ViewGridLanguage.Spanish]="Mosaico / Tarjeta", [ViewGridLanguage.Italian]="Riquadro / Scheda", [ViewGridLanguage.Russian]="Плитка / Карточка", [ViewGridLanguage.Arabic]="بطاقة / مربع", [ViewGridLanguage.Chinese]="磁贴 / 卡片", [ViewGridLanguage.Japanese]="タイル / カード" },

        ["Columns"] = new() { [ViewGridLanguage.Turkish]="Kolonlar", [ViewGridLanguage.English]="Columns", [ViewGridLanguage.German]="Spalten", [ViewGridLanguage.French]="Colonnes", [ViewGridLanguage.Spanish]="Columnas", [ViewGridLanguage.Italian]="Colonne", [ViewGridLanguage.Russian]="Столбцы", [ViewGridLanguage.Arabic]="الأعمدة", [ViewGridLanguage.Chinese]="列", [ViewGridLanguage.Japanese]="列" },
        ["ShowAll"] = new() { [ViewGridLanguage.Turkish]="Tümünü göster", [ViewGridLanguage.English]="Show all", [ViewGridLanguage.German]="Alle anzeigen", [ViewGridLanguage.French]="Tout afficher", [ViewGridLanguage.Spanish]="Mostrar todo", [ViewGridLanguage.Italian]="Mostra tutto", [ViewGridLanguage.Russian]="Показать все", [ViewGridLanguage.Arabic]="إظهار الكل", [ViewGridLanguage.Chinese]="全部显示", [ViewGridLanguage.Japanese]="すべて表示" },
        ["HideAll"] = new() { [ViewGridLanguage.Turkish]="Tümünü gizle", [ViewGridLanguage.English]="Hide all", [ViewGridLanguage.German]="Alle ausblenden", [ViewGridLanguage.French]="Tout masquer", [ViewGridLanguage.Spanish]="Ocultar todo", [ViewGridLanguage.Italian]="Nascondi tutto", [ViewGridLanguage.Russian]="Скрыть все", [ViewGridLanguage.Arabic]="إخفاء الكل", [ViewGridLanguage.Chinese]="全部隐藏", [ViewGridLanguage.Japanese]="すべて非表示" },
        ["DefaultColumnLayout"] = new() { [ViewGridLanguage.Turkish]="Varsayılan kolon düzeni", [ViewGridLanguage.English]="Default column layout", [ViewGridLanguage.German]="Standard-Spaltenlayout", [ViewGridLanguage.French]="Disposition de colonnes par défaut", [ViewGridLanguage.Spanish]="Diseño de columnas predeterminado", [ViewGridLanguage.Italian]="Layout colonne predefinito", [ViewGridLanguage.Russian]="Стандартный порядок столбцов", [ViewGridLanguage.Arabic]="تخطيط الأعمدة الافتراضي", [ViewGridLanguage.Chinese]="默认列布局", [ViewGridLanguage.Japanese]="既定の列レイアウト" },
        ["FitVisibleColumns"] = new() { [ViewGridLanguage.Turkish]="Görünür kolonları sığdır", [ViewGridLanguage.English]="Fit visible columns", [ViewGridLanguage.German]="Sichtbare Spalten anpassen", [ViewGridLanguage.French]="Ajuster les colonnes visibles", [ViewGridLanguage.Spanish]="Ajustar columnas visibles", [ViewGridLanguage.Italian]="Adatta colonne visibili", [ViewGridLanguage.Russian]="Подогнать видимые столбцы", [ViewGridLanguage.Arabic]="ملاءمة الأعمدة المرئية", [ViewGridLanguage.Chinese]="适应可见列", [ViewGridLanguage.Japanese]="表示列を合わせる" },
        ["ColumnChooserWindow"] = new() { [ViewGridLanguage.Turkish]="Kolon seçici penceresi...", [ViewGridLanguage.English]="Column chooser window...", [ViewGridLanguage.German]="Spaltenauswahlfenster...", [ViewGridLanguage.French]="Fenêtre de sélection des colonnes...", [ViewGridLanguage.Spanish]="Ventana de selección de columnas...", [ViewGridLanguage.Italian]="Finestra selettore colonne...", [ViewGridLanguage.Russian]="Окно выбора столбцов...", [ViewGridLanguage.Arabic]="نافذة اختيار الأعمدة...", [ViewGridLanguage.Chinese]="列选择窗口...", [ViewGridLanguage.Japanese]="列選択ウィンドウ..." },
        ["ColumnSearchPlaceholder"] = new() { [ViewGridLanguage.Turkish]="Kolon ara...", [ViewGridLanguage.English]="Search columns...", [ViewGridLanguage.German]="Spalten suchen...", [ViewGridLanguage.French]="Rechercher des colonnes...", [ViewGridLanguage.Spanish]="Buscar columnas...", [ViewGridLanguage.Italian]="Cerca colonne...", [ViewGridLanguage.Russian]="Поиск столбцов...", [ViewGridLanguage.Arabic]="بحث في الأعمدة...", [ViewGridLanguage.Chinese]="搜索列...", [ViewGridLanguage.Japanese]="列を検索..." },
        ["Cancel"] = new() { [ViewGridLanguage.Turkish]="İptal", [ViewGridLanguage.English]="Cancel", [ViewGridLanguage.German]="Abbrechen", [ViewGridLanguage.French]="Annuler", [ViewGridLanguage.Spanish]="Cancelar", [ViewGridLanguage.Italian]="Annulla", [ViewGridLanguage.Russian]="Отмена", [ViewGridLanguage.Arabic]="إلغاء", [ViewGridLanguage.Chinese]="取消", [ViewGridLanguage.Japanese]="キャンセル" },
        ["ClearColumnFilter"] = new() { [ViewGridLanguage.Turkish]="Bu kolonun filtresini temizle", [ViewGridLanguage.English]="Clear this column filter", [ViewGridLanguage.German]="Filter dieser Spalte löschen", [ViewGridLanguage.French]="Effacer le filtre de cette colonne", [ViewGridLanguage.Spanish]="Borrar filtro de esta columna", [ViewGridLanguage.Italian]="Cancella filtro colonna", [ViewGridLanguage.Russian]="Очистить фильтр столбца", [ViewGridLanguage.Arabic]="مسح فلتر هذا العمود", [ViewGridLanguage.Chinese]="清除此列筛选", [ViewGridLanguage.Japanese]="この列のフィルターをクリア" },
        ["CopyCell"] = new() { [ViewGridLanguage.Turkish]="Hücreyi kopyala", [ViewGridLanguage.English]="Copy cell", [ViewGridLanguage.German]="Zelle kopieren", [ViewGridLanguage.French]="Copier la cellule", [ViewGridLanguage.Spanish]="Copiar celda", [ViewGridLanguage.Italian]="Copia cella", [ViewGridLanguage.Russian]="Копировать ячейку", [ViewGridLanguage.Arabic]="نسخ الخلية", [ViewGridLanguage.Chinese]="复制单元格", [ViewGridLanguage.Japanese]="セルをコピー" },
        ["CopySelectionJson"] = new() { [ViewGridLanguage.Turkish]="Seçimi JSON kopyala", [ViewGridLanguage.English]="Copy selection as JSON", [ViewGridLanguage.German]="Auswahl als JSON kopieren", [ViewGridLanguage.French]="Copier la sélection en JSON", [ViewGridLanguage.Spanish]="Copiar selección como JSON", [ViewGridLanguage.Italian]="Copia selezione come JSON", [ViewGridLanguage.Russian]="Копировать выбор как JSON", [ViewGridLanguage.Arabic]="نسخ التحديد كـ JSON", [ViewGridLanguage.Chinese]="复制选择为 JSON", [ViewGridLanguage.Japanese]="選択をJSONでコピー" },
        ["CopyMiniAnalytics"] = new() { [ViewGridLanguage.Turkish]="Mini analytics kopyala", [ViewGridLanguage.English]="Copy mini analytics", [ViewGridLanguage.German]="Mini-Analyse kopieren", [ViewGridLanguage.French]="Copier la mini-analyse", [ViewGridLanguage.Spanish]="Copiar mini análisis", [ViewGridLanguage.Italian]="Copia mini analisi", [ViewGridLanguage.Russian]="Копировать мини-аналитику", [ViewGridLanguage.Arabic]="نسخ التحليل المصغر", [ViewGridLanguage.Chinese]="复制迷你分析", [ViewGridLanguage.Japanese]="ミニ分析をコピー" },
        ["Mode"] = new() { [ViewGridLanguage.Turkish]="Çalışma modu", [ViewGridLanguage.English]="Mode", [ViewGridLanguage.German]="Modus", [ViewGridLanguage.French]="Mode", [ViewGridLanguage.Spanish]="Modo", [ViewGridLanguage.Italian]="Modalità", [ViewGridLanguage.Russian]="Режим", [ViewGridLanguage.Arabic]="الوضع", [ViewGridLanguage.Chinese]="模式", [ViewGridLanguage.Japanese]="モード" },
        ["Theme"] = new() { [ViewGridLanguage.Turkish]="Tema", [ViewGridLanguage.English]="Theme", [ViewGridLanguage.German]="Design", [ViewGridLanguage.French]="Thème", [ViewGridLanguage.Spanish]="Tema", [ViewGridLanguage.Italian]="Tema", [ViewGridLanguage.Russian]="Тема", [ViewGridLanguage.Arabic]="السمة", [ViewGridLanguage.Chinese]="主题", [ViewGridLanguage.Japanese]="テーマ" },
        ["Sorting"] = new() { [ViewGridLanguage.Turkish]="Sıralama", [ViewGridLanguage.English]="Sorting", [ViewGridLanguage.German]="Sortierung", [ViewGridLanguage.French]="Tri", [ViewGridLanguage.Spanish]="Ordenación", [ViewGridLanguage.Italian]="Ordinamento", [ViewGridLanguage.Russian]="Сортировка", [ViewGridLanguage.Arabic]="الترتيب", [ViewGridLanguage.Chinese]="排序", [ViewGridLanguage.Japanese]="並べ替え" },
        ["FrozenColumn"] = new() { [ViewGridLanguage.Turkish]="Sabit kolon", [ViewGridLanguage.English]="Frozen column", [ViewGridLanguage.German]="Fixierte Spalte", [ViewGridLanguage.French]="Colonne figée", [ViewGridLanguage.Spanish]="Columna fijada", [ViewGridLanguage.Italian]="Colonna bloccata", [ViewGridLanguage.Russian]="Закрепленный столбец", [ViewGridLanguage.Arabic]="عمود مثبت", [ViewGridLanguage.Chinese]="冻结列", [ViewGridLanguage.Japanese]="固定列" },
        ["ColumnWidth"] = new() { [ViewGridLanguage.Turkish]="Kolon genişliği", [ViewGridLanguage.English]="Column width", [ViewGridLanguage.German]="Spaltenbreite", [ViewGridLanguage.French]="Largeur de colonne", [ViewGridLanguage.Spanish]="Ancho de columna", [ViewGridLanguage.Italian]="Larghezza colonna", [ViewGridLanguage.Russian]="Ширина столбца", [ViewGridLanguage.Arabic]="عرض العمود", [ViewGridLanguage.Chinese]="列宽", [ViewGridLanguage.Japanese]="列幅" },
        ["Layout"] = new() { [ViewGridLanguage.Turkish]="Düzen", [ViewGridLanguage.English]="Layout", [ViewGridLanguage.German]="Layout", [ViewGridLanguage.French]="Disposition", [ViewGridLanguage.Spanish]="Diseño", [ViewGridLanguage.Italian]="Layout", [ViewGridLanguage.Russian]="Макет", [ViewGridLanguage.Arabic]="التخطيط", [ViewGridLanguage.Chinese]="布局", [ViewGridLanguage.Japanese]="レイアウト" },
        ["SaveDefaultLayoutProfile"] = new() { [ViewGridLanguage.Turkish]="Layout profilini kaydet: Default", [ViewGridLanguage.English]="Save layout profile: Default", [ViewGridLanguage.German]="Layoutprofil speichern: Default", [ViewGridLanguage.French]="Enregistrer le profil : Default", [ViewGridLanguage.Spanish]="Guardar perfil: Default", [ViewGridLanguage.Italian]="Salva profilo: Default", [ViewGridLanguage.Russian]="Сохранить профиль: Default", [ViewGridLanguage.Arabic]="حفظ ملف التخطيط: Default", [ViewGridLanguage.Chinese]="保存布局配置: Default", [ViewGridLanguage.Japanese]="レイアウトプロファイル保存: Default" },
        ["LayoutProfiles"] = new() { [ViewGridLanguage.Turkish]="Layout profilleri", [ViewGridLanguage.English]="Layout profiles", [ViewGridLanguage.German]="Layoutprofile", [ViewGridLanguage.French]="Profils de disposition", [ViewGridLanguage.Spanish]="Perfiles de diseño", [ViewGridLanguage.Italian]="Profili layout", [ViewGridLanguage.Russian]="Профили макета", [ViewGridLanguage.Arabic]="ملفات التخطيط", [ViewGridLanguage.Chinese]="布局配置", [ViewGridLanguage.Japanese]="レイアウトプロファイル" },
        ["SaveUserLayout"] = new() { [ViewGridLanguage.Turkish]="Kullanıcı düzenini kaydet", [ViewGridLanguage.English]="Save user layout", [ViewGridLanguage.German]="Benutzerlayout speichern", [ViewGridLanguage.French]="Enregistrer la disposition utilisateur", [ViewGridLanguage.Spanish]="Guardar diseño de usuario", [ViewGridLanguage.Italian]="Salva layout utente", [ViewGridLanguage.Russian]="Сохранить макет пользователя", [ViewGridLanguage.Arabic]="حفظ تخطيط المستخدم", [ViewGridLanguage.Chinese]="保存用户布局", [ViewGridLanguage.Japanese]="ユーザーレイアウトを保存" },
        ["LoadUserLayout"] = new() { [ViewGridLanguage.Turkish]="Kullanıcı düzenini yükle", [ViewGridLanguage.English]="Load user layout", [ViewGridLanguage.German]="Benutzerlayout laden", [ViewGridLanguage.French]="Charger la disposition utilisateur", [ViewGridLanguage.Spanish]="Cargar diseño de usuario", [ViewGridLanguage.Italian]="Carica layout utente", [ViewGridLanguage.Russian]="Загрузить макет пользователя", [ViewGridLanguage.Arabic]="تحميل تخطيط المستخدم", [ViewGridLanguage.Chinese]="加载用户布局", [ViewGridLanguage.Japanese]="ユーザーレイアウトを読み込み" },
        ["ResetUserLayout"] = new() { [ViewGridLanguage.Turkish]="Kullanıcı düzenini varsayılana döndür", [ViewGridLanguage.English]="Reset user layout to default", [ViewGridLanguage.German]="Benutzerlayout zurücksetzen", [ViewGridLanguage.French]="Réinitialiser la disposition utilisateur", [ViewGridLanguage.Spanish]="Restablecer diseño de usuario", [ViewGridLanguage.Italian]="Reimposta layout utente", [ViewGridLanguage.Russian]="Сбросить макет пользователя", [ViewGridLanguage.Arabic]="إعادة ضبط تخطيط المستخدم", [ViewGridLanguage.Chinese]="重置用户布局", [ViewGridLanguage.Japanese]="ユーザーレイアウトをリセット" },
        ["ExportUserLayout"] = new() { [ViewGridLanguage.Turkish]="Kullanıcı düzenini dışa aktar...", [ViewGridLanguage.English]="Export user layout...", [ViewGridLanguage.German]="Benutzerlayout exportieren...", [ViewGridLanguage.French]="Exporter la disposition utilisateur...", [ViewGridLanguage.Spanish]="Exportar diseño de usuario...", [ViewGridLanguage.Italian]="Esporta layout utente...", [ViewGridLanguage.Russian]="Экспорт макета пользователя...", [ViewGridLanguage.Arabic]="تصدير تخطيط المستخدم...", [ViewGridLanguage.Chinese]="导出用户布局...", [ViewGridLanguage.Japanese]="ユーザーレイアウトを書き出し..." },
        ["ImportUserLayout"] = new() { [ViewGridLanguage.Turkish]="Kullanıcı düzenini içe aktar...", [ViewGridLanguage.English]="Import user layout...", [ViewGridLanguage.German]="Benutzerlayout importieren...", [ViewGridLanguage.French]="Importer la disposition utilisateur...", [ViewGridLanguage.Spanish]="Importar diseño de usuario...", [ViewGridLanguage.Italian]="Importa layout utente...", [ViewGridLanguage.Russian]="Импорт макета пользователя...", [ViewGridLanguage.Arabic]="استيراد تخطيط المستخدم...", [ViewGridLanguage.Chinese]="导入用户布局...", [ViewGridLanguage.Japanese]="ユーザーレイアウトを読み込み..." },
        ["Grouping"] = new() { [ViewGridLanguage.Turkish]="Gruplama", [ViewGridLanguage.English]="Grouping", [ViewGridLanguage.German]="Gruppierung", [ViewGridLanguage.French]="Regroupement", [ViewGridLanguage.Spanish]="Agrupación", [ViewGridLanguage.Italian]="Raggruppamento", [ViewGridLanguage.Russian]="Группировка", [ViewGridLanguage.Arabic]="التجميع", [ViewGridLanguage.Chinese]="分组", [ViewGridLanguage.Japanese]="グループ化" },
        ["Freeze"] = new() { [ViewGridLanguage.Turkish]="Sabitleme", [ViewGridLanguage.English]="Freeze", [ViewGridLanguage.German]="Fixieren", [ViewGridLanguage.French]="Figer", [ViewGridLanguage.Spanish]="Fijar", [ViewGridLanguage.Italian]="Blocca", [ViewGridLanguage.Russian]="Закрепить", [ViewGridLanguage.Arabic]="تثبيت", [ViewGridLanguage.Chinese]="冻结", [ViewGridLanguage.Japanese]="固定" },
        ["View"] = new() { [ViewGridLanguage.Turkish]="Görünüm", [ViewGridLanguage.English]="View", [ViewGridLanguage.German]="Ansicht", [ViewGridLanguage.French]="Vue", [ViewGridLanguage.Spanish]="Vista", [ViewGridLanguage.Italian]="Vista", [ViewGridLanguage.Russian]="Вид", [ViewGridLanguage.Arabic]="العرض", [ViewGridLanguage.Chinese]="视图", [ViewGridLanguage.Japanese]="表示" },
        ["Clipboard"] = new() { [ViewGridLanguage.Turkish]="Pano", [ViewGridLanguage.English]="Clipboard", [ViewGridLanguage.German]="Zwischenablage", [ViewGridLanguage.French]="Presse-papiers", [ViewGridLanguage.Spanish]="Portapapeles", [ViewGridLanguage.Italian]="Appunti", [ViewGridLanguage.Russian]="Буфер обмена", [ViewGridLanguage.Arabic]="الحافظة", [ViewGridLanguage.Chinese]="剪贴板", [ViewGridLanguage.Japanese]="クリップボード" },
        ["Editing"] = new() { [ViewGridLanguage.Turkish]="Düzenleme", [ViewGridLanguage.English]="Editing", [ViewGridLanguage.German]="Bearbeiten", [ViewGridLanguage.French]="Édition", [ViewGridLanguage.Spanish]="Edición", [ViewGridLanguage.Italian]="Modifica", [ViewGridLanguage.Russian]="Редактирование", [ViewGridLanguage.Arabic]="التحرير", [ViewGridLanguage.Chinese]="编辑", [ViewGridLanguage.Japanese]="編集" },
        ["Analytics"] = new() { [ViewGridLanguage.Turkish]="Analiz", [ViewGridLanguage.English]="Analytics", [ViewGridLanguage.German]="Analyse", [ViewGridLanguage.French]="Analyse", [ViewGridLanguage.Spanish]="Análisis", [ViewGridLanguage.Italian]="Analisi", [ViewGridLanguage.Russian]="Аналитика", [ViewGridLanguage.Arabic]="التحليلات", [ViewGridLanguage.Chinese]="分析", [ViewGridLanguage.Japanese]="分析" },
        ["BuiltInHeaderMenu"] = new() { [ViewGridLanguage.Turkish]="Kolon / filtre özellikleri", [ViewGridLanguage.English]="Column / filter options", [ViewGridLanguage.German]="Spalten-/Filteroptionen", [ViewGridLanguage.French]="Options colonne / filtre", [ViewGridLanguage.Spanish]="Opciones de columna / filtro", [ViewGridLanguage.Italian]="Opzioni colonna / filtro", [ViewGridLanguage.Russian]="Параметры столбца / фильтра", [ViewGridLanguage.Arabic]="خيارات العمود / التصفية", [ViewGridLanguage.Chinese]="列 / 筛选选项", [ViewGridLanguage.Japanese]="列 / フィルターオプション" },
        ["ViewGridDataMode_Object"] = new() { [ViewGridLanguage.Turkish]="Nesne", [ViewGridLanguage.English]="Object", [ViewGridLanguage.German]="Objekt", [ViewGridLanguage.French]="Objet", [ViewGridLanguage.Spanish]="Objeto", [ViewGridLanguage.Italian]="Oggetto", [ViewGridLanguage.Russian]="Объект", [ViewGridLanguage.Arabic]="كائن", [ViewGridLanguage.Chinese]="对象", [ViewGridLanguage.Japanese]="オブジェクト" },
        ["ViewGridDataMode_DataTable"] = new() { [ViewGridLanguage.Turkish]="DataTable", [ViewGridLanguage.English]="DataTable", [ViewGridLanguage.German]="Datentabelle", [ViewGridLanguage.French]="Table de données", [ViewGridLanguage.Spanish]="Tabla de datos", [ViewGridLanguage.Italian]="Tabella dati", [ViewGridLanguage.Russian]="Таблица данных", [ViewGridLanguage.Arabic]="جدول بيانات", [ViewGridLanguage.Chinese]="数据表", [ViewGridLanguage.Japanese]="データテーブル" },
        ["ViewGridDataMode_Virtual"] = new() { [ViewGridLanguage.Turkish]="Sanal", [ViewGridLanguage.English]="Virtual", [ViewGridLanguage.German]="Virtuell", [ViewGridLanguage.French]="Virtuel", [ViewGridLanguage.Spanish]="Virtual", [ViewGridLanguage.Italian]="Virtuale", [ViewGridLanguage.Russian]="Виртуальный", [ViewGridLanguage.Arabic]="افتراضي", [ViewGridLanguage.Chinese]="虚拟", [ViewGridLanguage.Japanese]="仮想" },
        ["ViewGridDataMode_Tree"] = new() { [ViewGridLanguage.Turkish]="Ağaç", [ViewGridLanguage.English]="Tree", [ViewGridLanguage.German]="Baum", [ViewGridLanguage.French]="Arbre", [ViewGridLanguage.Spanish]="Árbol", [ViewGridLanguage.Italian]="Albero", [ViewGridLanguage.Russian]="Дерево", [ViewGridLanguage.Arabic]="شجرة", [ViewGridLanguage.Chinese]="树", [ViewGridLanguage.Japanese]="ツリー" },
        ["ViewGridDataMode_Tile"] = new() { [ViewGridLanguage.Turkish]="Kart", [ViewGridLanguage.English]="Tile", [ViewGridLanguage.German]="Kachel", [ViewGridLanguage.French]="Tuile", [ViewGridLanguage.Spanish]="Mosaico", [ViewGridLanguage.Italian]="Riquadro", [ViewGridLanguage.Russian]="Плитка", [ViewGridLanguage.Arabic]="بطاقة", [ViewGridLanguage.Chinese]="磁贴", [ViewGridLanguage.Japanese]="タイル" },
        ["Theme_System"] = new() { [ViewGridLanguage.Turkish]="Sistem", [ViewGridLanguage.English]="System", [ViewGridLanguage.German]="System", [ViewGridLanguage.French]="Système", [ViewGridLanguage.Spanish]="Sistema", [ViewGridLanguage.Italian]="Sistema", [ViewGridLanguage.Russian]="Система", [ViewGridLanguage.Arabic]="النظام", [ViewGridLanguage.Chinese]="系统", [ViewGridLanguage.Japanese]="システム" },
        ["Theme_Light"] = new() { [ViewGridLanguage.Turkish]="Açık", [ViewGridLanguage.English]="Light", [ViewGridLanguage.German]="Hell", [ViewGridLanguage.French]="Clair", [ViewGridLanguage.Spanish]="Claro", [ViewGridLanguage.Italian]="Chiaro", [ViewGridLanguage.Russian]="Светлая", [ViewGridLanguage.Arabic]="فاتح", [ViewGridLanguage.Chinese]="浅色", [ViewGridLanguage.Japanese]="ライト" },
        ["Theme_Dark"] = new() { [ViewGridLanguage.Turkish]="Koyu", [ViewGridLanguage.English]="Dark", [ViewGridLanguage.German]="Dunkel", [ViewGridLanguage.French]="Sombre", [ViewGridLanguage.Spanish]="Oscuro", [ViewGridLanguage.Italian]="Scuro", [ViewGridLanguage.Russian]="Темная", [ViewGridLanguage.Arabic]="داكن", [ViewGridLanguage.Chinese]="深色", [ViewGridLanguage.Japanese]="ダーク" },
        ["Theme_FluentLight"] = new() { [ViewGridLanguage.Turkish]="Fluent Açık", [ViewGridLanguage.English]="Fluent Light", [ViewGridLanguage.German]="Fluent Hell", [ViewGridLanguage.French]="Fluent clair", [ViewGridLanguage.Spanish]="Fluent claro", [ViewGridLanguage.Italian]="Fluent chiaro", [ViewGridLanguage.Russian]="Fluent светлая", [ViewGridLanguage.Arabic]="Fluent فاتح", [ViewGridLanguage.Chinese]="Fluent 浅色", [ViewGridLanguage.Japanese]="Fluent ライト" },
        ["Theme_FluentDark"] = new() { [ViewGridLanguage.Turkish]="Fluent Koyu", [ViewGridLanguage.English]="Fluent Dark", [ViewGridLanguage.German]="Fluent Dunkel", [ViewGridLanguage.French]="Fluent sombre", [ViewGridLanguage.Spanish]="Fluent oscuro", [ViewGridLanguage.Italian]="Fluent scuro", [ViewGridLanguage.Russian]="Fluent темная", [ViewGridLanguage.Arabic]="Fluent داكن", [ViewGridLanguage.Chinese]="Fluent 深色", [ViewGridLanguage.Japanese]="Fluent ダーク" },
        ["BuiltInMenuMergeText"] = new() { [ViewGridLanguage.Turkish]="Liste özellikleri", [ViewGridLanguage.English]="List options", [ViewGridLanguage.German]="Listenoptionen", [ViewGridLanguage.French]="Options de liste", [ViewGridLanguage.Spanish]="Opciones de lista", [ViewGridLanguage.Italian]="Opzioni elenco", [ViewGridLanguage.Russian]="Параметры списка", [ViewGridLanguage.Arabic]="خيارات القائمة", [ViewGridLanguage.Chinese]="列表选项", [ViewGridLanguage.Japanese]="リストオプション" },
        ["FastPreviewLimitedInfo"] = new() { [ViewGridLanguage.Turkish]="İlk açılış hızlı önizlemedir. 3+ karakter yazınca tüm veri kaynağı arka planda taranır.", [ViewGridLanguage.English]="First opening is a fast preview. Type 3+ characters to scan the full data source in the background.", [ViewGridLanguage.German]="Beim ersten Öffnen wird eine Schnellvorschau angezeigt. Ab 3 Zeichen wird die gesamte Datenquelle im Hintergrund durchsucht.", [ViewGridLanguage.French]="La première ouverture est un aperçu rapide. Tapez au moins 3 caractères pour analyser toute la source en arrière-plan.", [ViewGridLanguage.Spanish]="La primera apertura es una vista rápida. Escriba 3+ caracteres para buscar en toda la fuente en segundo plano.", [ViewGridLanguage.Italian]="La prima apertura è un'anteprima rapida. Digita almeno 3 caratteri per analizzare l'intera origine dati in background.", [ViewGridLanguage.Russian]="Первое открытие — быстрый предпросмотр. Введите 3+ символа, чтобы просканировать весь источник данных в фоне.", [ViewGridLanguage.Arabic]="الفتح الأول معاينة سريعة. اكتب 3 أحرف أو أكثر لفحص مصدر البيانات كاملاً في الخلفية.", [ViewGridLanguage.Chinese]="首次打开为快速预览。输入 3 个以上字符将在后台扫描完整数据源。", [ViewGridLanguage.Japanese]="初回表示は高速プレビューです。3文字以上入力すると全データソースをバックグラウンドで検索します。" },
        ["SearchingPreviewResults"] = new() { [ViewGridLanguage.Turkish]="Aranıyor... Liste ilk sonuçları gösteriyor", [ViewGridLanguage.English]="Searching... The list shows initial results", [ViewGridLanguage.German]="Suche läuft... Die Liste zeigt erste Ergebnisse", [ViewGridLanguage.French]="Recherche... La liste affiche les premiers résultats", [ViewGridLanguage.Spanish]="Buscando... La lista muestra los primeros resultados", [ViewGridLanguage.Italian]="Ricerca... L'elenco mostra i primi risultati", [ViewGridLanguage.Russian]="Поиск... список показывает первые результаты", [ViewGridLanguage.Arabic]="جارٍ البحث... تعرض القائمة النتائج الأولى", [ViewGridLanguage.Chinese]="正在搜索... 列表显示初始结果", [ViewGridLanguage.Japanese]="検索中... リストに初期結果を表示しています" },
        ["PrintPreviewSuffix"] = new() { [ViewGridLanguage.Turkish]="Önizleme", [ViewGridLanguage.English]="Preview", [ViewGridLanguage.German]="Vorschau", [ViewGridLanguage.French]="Aperçu", [ViewGridLanguage.Spanish]="Vista previa", [ViewGridLanguage.Italian]="Anteprima", [ViewGridLanguage.Russian]="Предпросмотр", [ViewGridLanguage.Arabic]="معاينة", [ViewGridLanguage.Chinese]="预览", [ViewGridLanguage.Japanese]="プレビュー" },
        ["Posters"] = new() { [ViewGridLanguage.Turkish]="Poster / Resimli içerik", [ViewGridLanguage.English]="Poster / Image content", [ViewGridLanguage.German]="Poster / Bildinhalt", [ViewGridLanguage.French]="Affiche / contenu image", [ViewGridLanguage.Spanish]="Póster / contenido visual", [ViewGridLanguage.Italian]="Poster / contenuto immagine", [ViewGridLanguage.Russian]="Постер / изображение", [ViewGridLanguage.Arabic]="ملصق / محتوى مرئي", [ViewGridLanguage.Chinese]="海报 / 图片内容", [ViewGridLanguage.Japanese]="ポスター / 画像コンテンツ" }
    };

    public static ViewGridLanguage Language { get; set; } = ViewGridLanguage.Auto;
    public static IDictionary<string, string> CustomTranslations { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

    public static string ViewGridDataModeName(string name)
    {
        string key = "ViewGridDataMode_" + name;
        string value = T(key);
        return string.Equals(value, key, StringComparison.OrdinalIgnoreCase) ? name : value;
    }

    public static string ThemePresetName(string name)
    {
        string key = "Theme_" + name;
        string value = T(key);
        return string.Equals(value, key, StringComparison.OrdinalIgnoreCase) ? name : value;
    }

    public static void LoadCustomTranslations(string jsonFilePath)
    {
        if (!File.Exists(jsonFilePath)) return;
        var data = JsonSerializer.Deserialize<Dictionary<string, string>>(File.ReadAllText(jsonFilePath));
        if (data == null) return;
        foreach (var kv in data) CustomTranslations[kv.Key] = kv.Value;
    }

    public static ViewGridLanguage EffectiveLanguage
    {
        get
        {
            if (Language != ViewGridLanguage.Auto) return Language;
            var two = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant();
            return two switch
            {
                "tr" => ViewGridLanguage.Turkish,
                "de" => ViewGridLanguage.German,
                "fr" => ViewGridLanguage.French,
                "es" => ViewGridLanguage.Spanish,
                "it" => ViewGridLanguage.Italian,
                "ru" => ViewGridLanguage.Russian,
                "ar" => ViewGridLanguage.Arabic,
                "zh" => ViewGridLanguage.Chinese,
                "ja" => ViewGridLanguage.Japanese,
                _ => ViewGridLanguage.English
            };
        }
    }

    public static string T(string key)
    {
        if (CustomTranslations.TryGetValue(key, out var custom)) return custom;
        if (!Texts.TryGetValue(key, out var perLang)) return key;
        var lang = EffectiveLanguage;
        if (perLang.TryGetValue(lang, out var value)) return value;
        return perLang.TryGetValue(ViewGridLanguage.English, out var en) ? en : key;
    }

    public static string Filtering => T("Filtering");
    public static string FilterWindow(string column) => $"'{column}' {T("FilterWindowSuffix")}";
    public static string FilterStyle => T("FilterStyle");
    public static string SortAscending => T("SortAscending");
    public static string SortDescending => T("SortDescending");
    public static string Unsort => T("Unsort");
    public static string ClearSort => T("ClearSort");
    public static string UnsortColumn => T("UnsortColumn");
    public static string FreezeColumn => T("FreezeColumn");
    public static string ClearFrozenColumns => T("ClearFrozenColumns");
    public static string AutoSizeColumn => T("AutoSizeColumn");
    public static string AutoSizeAllColumns => T("AutoSizeAllColumns");
    public static string GroupByColumn(string column) => $"{T("GroupByColumnPrefix")} {column}";
    public static string CollapseAllGroups => T("CollapseAllGroups");
    public static string ExpandAllGroups => T("ExpandAllGroups");
    public static string ClearGrouping => T("ClearGrouping");
    public static string CollapseThisGroup => T("CollapseThisGroup");
    public static string ExpandThisGroup => T("ExpandThisGroup");
    public static string ShowOnlyThisGroup => T("ShowOnlyThisGroup");
    public static string ViewMode => T("ViewMode");
    public static string ChooseColumns => T("ChooseColumns");
    public static string ClearFilters => T("ClearFilters");
    public static string ClearAllFilters => T("ClearAllFilters");
    public static string ColumnFilterTitle(string column) => $"{column} {T("ColumnFilterSuffix")}";
    public static string SearchPlaceholder => T("SearchPlaceholder");
    public static string ApplyTypedTextAsFilter => T("ApplyTypedTextAsFilter");
    public static string SearchTypedTextInColumn => T("SearchTypedTextInColumn");
    public static string SelectAll => T("SelectAll");
    public static string Apply => T("Apply");
    public static string Clear => T("Clear");
    public static string SeparateFilterWindow => T("SeparateFilterWindow");
    public static string EmptyList => T("EmptyList");
    public static string EmptyValue => T("EmptyValue");
    public static string Copy => T("Copy");
    public static string Paste => T("Paste");
    public static string EditCell => T("EditCell");
    public static string RowDetails => T("RowDetails");
    public static string PopupMenu => T("PopupMenu");
    public static string ModalWindow => T("ModalWindow");
    public static string Both => T("Both");
    public static string ExtraLarge => T("ExtraLarge");
    public static string Large => T("Large");
    public static string Medium => T("Medium");
    public static string List => T("List");
    public static string Details => T("Details");
    public static string Tiles => T("Tiles");
    public static string Posters => T("Posters");
    public static string Columns => T("Columns");
    public static string ShowAll => T("ShowAll");
    public static string HideAll => T("HideAll");
    public static string DefaultColumnLayout => T("DefaultColumnLayout");
    public static string FitVisibleColumns => T("FitVisibleColumns");
    public static string ColumnChooserWindow => T("ColumnChooserWindow");
    public static string ColumnSearchPlaceholder => T("ColumnSearchPlaceholder");
    public static string Cancel => T("Cancel");
    public static string ClearColumnFilter => T("ClearColumnFilter");
    public static string CopyCell => T("CopyCell");
    public static string CopySelectionJson => T("CopySelectionJson");
    public static string CopyMiniAnalytics => T("CopyMiniAnalytics");
    public static string Mode => T("Mode");
    public static string Theme => T("Theme");
    public static string Sorting => T("Sorting");
    public static string FrozenColumn => T("FrozenColumn");
    public static string ColumnWidth => T("ColumnWidth");
    public static string Layout => T("Layout");
    public static string SaveDefaultLayoutProfile => T("SaveDefaultLayoutProfile");
    public static string LayoutProfiles => T("LayoutProfiles");
    public static string SaveUserLayout => T("SaveUserLayout");
    public static string LoadUserLayout => T("LoadUserLayout");
    public static string ResetUserLayout => T("ResetUserLayout");
    public static string ExportUserLayout => T("ExportUserLayout");
    public static string ImportUserLayout => T("ImportUserLayout");
    public static string Grouping => T("Grouping");
    public static string Freeze => T("Freeze");
    public static string View => T("View");
    public static string Clipboard => T("Clipboard");
    public static string Editing => T("Editing");
    public static string Analytics => T("Analytics");
    public static string BuiltInHeaderMenu => T("BuiltInHeaderMenu");
    public static string BuiltInMenuMergeText => T("BuiltInMenuMergeText");
    public static string FastPreviewLimitedInfo => T("FastPreviewLimitedInfo");
    public static string SearchingPreviewResults => T("SearchingPreviewResults");
    public static string PrintPreviewSuffix => T("PrintPreviewSuffix");

    public static string SaveColumnLayout => T("SaveColumnLayout");
    public static string LoadColumnLayout => T("LoadColumnLayout");
    public static string ResetColumnLayout => T("ResetColumnLayout");
    public static string ColumnChooserTitle => T("ColumnChooserTitle");
    public static string OK => T("OK");
    public static string FastPreviewInfo => T("FastPreviewInfo");
}

